// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<7> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_ST_fsm_state1 = "1";
const sc_lv<7> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_ST_fsm_state2 = "10";
const sc_lv<7> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_ST_fsm_state3 = "100";
const sc_lv<7> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_ST_fsm_state4 = "1000";
const sc_lv<7> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_ST_fsm_state5 = "10000";
const sc_lv<7> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_ST_fsm_state6 = "100000";
const sc_lv<7> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_ST_fsm_state7 = "1000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_1 = "1";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_4 = "100";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_3 = "11";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_5 = "101";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_2 = "10";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_8 = "1000";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_1 = "1";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_2 = "10";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_3 = "11";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_4 = "100";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_5 = "101";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_6 = "110";
const sc_lv<64> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv64_7 = "111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_6 = "110";
const sc_lv<1> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv1_1 = "1";
const sc_lv<3> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv3_4 = "100";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_60 = "1100000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_7F = "1111111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_10 = "10000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_2F = "101111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_1F = "11111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_30 = "110000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_4F = "1001111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_20 = "100000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_3F = "111111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_40 = "1000000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_50 = "1010000";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_5F = "1011111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_6F = "1101111";
const sc_lv<32> cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_lv32_70 = "1110000";
const bool cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::ap_const_boolean_1 = true;

cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    layer_in_row_Array_V_0_0_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_0_0_U");
    layer_in_row_Array_V_0_0_U->clk(ap_clk);
    layer_in_row_Array_V_0_0_U->reset(ap_rst);
    layer_in_row_Array_V_0_0_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_0_0_U->ce0(layer_in_row_Array_V_0_0_ce0);
    layer_in_row_Array_V_0_0_U->we0(layer_in_row_Array_V_0_0_we0);
    layer_in_row_Array_V_0_0_U->d0(trunc_ln203_reg_764);
    layer_in_row_Array_V_0_0_U->q0(layer_in_row_Array_V_0_0_q0);
    layer_in_row_Array_V_1_0_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_1_0_U");
    layer_in_row_Array_V_1_0_U->clk(ap_clk);
    layer_in_row_Array_V_1_0_U->reset(ap_rst);
    layer_in_row_Array_V_1_0_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_1_0_U->ce0(layer_in_row_Array_V_1_0_ce0);
    layer_in_row_Array_V_1_0_U->we0(layer_in_row_Array_V_1_0_we0);
    layer_in_row_Array_V_1_0_U->d0(layer_in_row_Array_V_0_0_q0);
    layer_in_row_Array_V_1_0_U->q0(layer_in_row_Array_V_1_0_q0);
    layer_in_row_Array_V_0_1_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_0_1_U");
    layer_in_row_Array_V_0_1_U->clk(ap_clk);
    layer_in_row_Array_V_0_1_U->reset(ap_rst);
    layer_in_row_Array_V_0_1_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_0_1_U->ce0(layer_in_row_Array_V_0_1_ce0);
    layer_in_row_Array_V_0_1_U->we0(layer_in_row_Array_V_0_1_we0);
    layer_in_row_Array_V_0_1_U->d0(DataIn_V_assign_2_reg_769);
    layer_in_row_Array_V_0_1_U->q0(layer_in_row_Array_V_0_1_q0);
    layer_in_row_Array_V_1_1_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_1_1_U");
    layer_in_row_Array_V_1_1_U->clk(ap_clk);
    layer_in_row_Array_V_1_1_U->reset(ap_rst);
    layer_in_row_Array_V_1_1_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_1_1_U->ce0(layer_in_row_Array_V_1_1_ce0);
    layer_in_row_Array_V_1_1_U->we0(layer_in_row_Array_V_1_1_we0);
    layer_in_row_Array_V_1_1_U->d0(DataOut_V_3_reg_871);
    layer_in_row_Array_V_1_1_U->q0(layer_in_row_Array_V_1_1_q0);
    layer_in_row_Array_V_0_2_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_0_2_U");
    layer_in_row_Array_V_0_2_U->clk(ap_clk);
    layer_in_row_Array_V_0_2_U->reset(ap_rst);
    layer_in_row_Array_V_0_2_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_0_2_U->ce0(layer_in_row_Array_V_0_2_ce0);
    layer_in_row_Array_V_0_2_U->we0(layer_in_row_Array_V_0_2_we0);
    layer_in_row_Array_V_0_2_U->d0(DataIn_V_assign_4_reg_775);
    layer_in_row_Array_V_0_2_U->q0(layer_in_row_Array_V_0_2_q0);
    layer_in_row_Array_V_1_2_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_1_2_U");
    layer_in_row_Array_V_1_2_U->clk(ap_clk);
    layer_in_row_Array_V_1_2_U->reset(ap_rst);
    layer_in_row_Array_V_1_2_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_1_2_U->ce0(layer_in_row_Array_V_1_2_ce0);
    layer_in_row_Array_V_1_2_U->we0(layer_in_row_Array_V_1_2_we0);
    layer_in_row_Array_V_1_2_U->d0(layer_in_row_Array_V_0_2_q0);
    layer_in_row_Array_V_1_2_U->q0(layer_in_row_Array_V_1_2_q0);
    layer_in_row_Array_V_0_3_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_0_3_U");
    layer_in_row_Array_V_0_3_U->clk(ap_clk);
    layer_in_row_Array_V_0_3_U->reset(ap_rst);
    layer_in_row_Array_V_0_3_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_0_3_U->ce0(layer_in_row_Array_V_0_3_ce0);
    layer_in_row_Array_V_0_3_U->we0(layer_in_row_Array_V_0_3_we0);
    layer_in_row_Array_V_0_3_U->d0(layer_in_row_Array_V_0_3_d0);
    layer_in_row_Array_V_0_3_U->q0(layer_in_row_Array_V_0_3_q0);
    layer_in_row_Array_V_1_3_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_1_3_U");
    layer_in_row_Array_V_1_3_U->clk(ap_clk);
    layer_in_row_Array_V_1_3_U->reset(ap_rst);
    layer_in_row_Array_V_1_3_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_1_3_U->ce0(layer_in_row_Array_V_1_3_ce0);
    layer_in_row_Array_V_1_3_U->we0(layer_in_row_Array_V_1_3_we0);
    layer_in_row_Array_V_1_3_U->d0(layer_in_row_Array_V_0_3_q0);
    layer_in_row_Array_V_1_3_U->q0(layer_in_row_Array_V_1_3_q0);
    layer_in_row_Array_V_0_4_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_0_4_U");
    layer_in_row_Array_V_0_4_U->clk(ap_clk);
    layer_in_row_Array_V_0_4_U->reset(ap_rst);
    layer_in_row_Array_V_0_4_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_0_4_U->ce0(layer_in_row_Array_V_0_4_ce0);
    layer_in_row_Array_V_0_4_U->we0(layer_in_row_Array_V_0_4_we0);
    layer_in_row_Array_V_0_4_U->d0(DataIn_V_assign_8_reg_791);
    layer_in_row_Array_V_0_4_U->q0(layer_in_row_Array_V_0_4_q0);
    layer_in_row_Array_V_1_4_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_1_4_U");
    layer_in_row_Array_V_1_4_U->clk(ap_clk);
    layer_in_row_Array_V_1_4_U->reset(ap_rst);
    layer_in_row_Array_V_1_4_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_1_4_U->ce0(layer_in_row_Array_V_1_4_ce0);
    layer_in_row_Array_V_1_4_U->we0(layer_in_row_Array_V_1_4_we0);
    layer_in_row_Array_V_1_4_U->d0(layer_in_row_Array_V_0_4_q0);
    layer_in_row_Array_V_1_4_U->q0(layer_in_row_Array_V_1_4_q0);
    layer_in_row_Array_V_0_5_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_0_5_U");
    layer_in_row_Array_V_0_5_U->clk(ap_clk);
    layer_in_row_Array_V_0_5_U->reset(ap_rst);
    layer_in_row_Array_V_0_5_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_0_5_U->ce0(layer_in_row_Array_V_0_5_ce0);
    layer_in_row_Array_V_0_5_U->we0(layer_in_row_Array_V_0_5_we0);
    layer_in_row_Array_V_0_5_U->d0(DataIn_V_assign_s_reg_797);
    layer_in_row_Array_V_0_5_U->q0(layer_in_row_Array_V_0_5_q0);
    layer_in_row_Array_V_1_5_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_1_5_U");
    layer_in_row_Array_V_1_5_U->clk(ap_clk);
    layer_in_row_Array_V_1_5_U->reset(ap_rst);
    layer_in_row_Array_V_1_5_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_1_5_U->ce0(layer_in_row_Array_V_1_5_ce0);
    layer_in_row_Array_V_1_5_U->we0(layer_in_row_Array_V_1_5_we0);
    layer_in_row_Array_V_1_5_U->d0(layer_in_row_Array_V_0_5_q0);
    layer_in_row_Array_V_1_5_U->q0(layer_in_row_Array_V_1_5_q0);
    layer_in_row_Array_V_0_6_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_0_6_U");
    layer_in_row_Array_V_0_6_U->clk(ap_clk);
    layer_in_row_Array_V_0_6_U->reset(ap_rst);
    layer_in_row_Array_V_0_6_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_0_6_U->ce0(layer_in_row_Array_V_0_6_ce0);
    layer_in_row_Array_V_0_6_U->we0(layer_in_row_Array_V_0_6_we0);
    layer_in_row_Array_V_0_6_U->d0(layer_in_row_Array_V_0_6_d0);
    layer_in_row_Array_V_0_6_U->q0(layer_in_row_Array_V_0_6_q0);
    layer_in_row_Array_V_1_6_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_1_6_U");
    layer_in_row_Array_V_1_6_U->clk(ap_clk);
    layer_in_row_Array_V_1_6_U->reset(ap_rst);
    layer_in_row_Array_V_1_6_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_1_6_U->ce0(layer_in_row_Array_V_1_6_ce0);
    layer_in_row_Array_V_1_6_U->we0(layer_in_row_Array_V_1_6_we0);
    layer_in_row_Array_V_1_6_U->d0(DataOut_V_12_reg_808);
    layer_in_row_Array_V_1_6_U->q0(layer_in_row_Array_V_1_6_q0);
    layer_in_row_Array_V_0_7_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_0_7_U");
    layer_in_row_Array_V_0_7_U->clk(ap_clk);
    layer_in_row_Array_V_0_7_U->reset(ap_rst);
    layer_in_row_Array_V_0_7_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_0_7_U->ce0(layer_in_row_Array_V_0_7_ce0);
    layer_in_row_Array_V_0_7_U->we0(layer_in_row_Array_V_0_7_we0);
    layer_in_row_Array_V_0_7_U->d0(DataIn_V_assign_3_reg_813);
    layer_in_row_Array_V_0_7_U->q0(layer_in_row_Array_V_0_7_q0);
    layer_in_row_Array_V_1_7_U = new cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb("layer_in_row_Array_V_1_7_U");
    layer_in_row_Array_V_1_7_U->clk(ap_clk);
    layer_in_row_Array_V_1_7_U->reset(ap_rst);
    layer_in_row_Array_V_1_7_U->address0(ap_var_for_const0);
    layer_in_row_Array_V_1_7_U->ce0(layer_in_row_Array_V_1_7_ce0);
    layer_in_row_Array_V_1_7_U->we0(layer_in_row_Array_V_1_7_we0);
    layer_in_row_Array_V_1_7_U->d0(layer_in_row_Array_V_0_7_q0);
    layer_in_row_Array_V_1_7_U->q0(layer_in_row_Array_V_1_7_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_244_p4);
    sensitive << ( output_V_q0 );

    SC_METHOD(thread_grp_fu_254_p4);
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_grp_fu_264_p4);
    sensitive << ( output_V_q0 );

    SC_METHOD(thread_grp_fu_274_p4);
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_grp_fu_284_p4);
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_grp_fu_294_p4);
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_layer_in_row_Array_V_0_0_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_layer_in_row_Array_V_0_0_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_layer_in_row_Array_V_0_1_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_layer_in_row_Array_V_0_1_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_layer_in_row_Array_V_0_2_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_layer_in_row_Array_V_0_2_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_layer_in_row_Array_V_0_3_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_layer_in_row_Array_V_0_3_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_port_reg_data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_0_3_we0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_layer_in_row_Array_V_0_4_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_layer_in_row_Array_V_0_4_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_layer_in_row_Array_V_0_5_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_layer_in_row_Array_V_0_5_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_layer_in_row_Array_V_0_6_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_layer_in_row_Array_V_0_6_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_port_reg_data_V_read );

    SC_METHOD(thread_layer_in_row_Array_V_0_6_we0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_layer_in_row_Array_V_0_7_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_layer_in_row_Array_V_0_7_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_layer_in_row_Array_V_1_0_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_layer_in_row_Array_V_1_0_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_layer_in_row_Array_V_1_1_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_layer_in_row_Array_V_1_1_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_layer_in_row_Array_V_1_2_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_layer_in_row_Array_V_1_2_we0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_layer_in_row_Array_V_1_3_ce0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_layer_in_row_Array_V_1_3_we0);
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_layer_in_row_Array_V_1_4_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_layer_in_row_Array_V_1_4_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_layer_in_row_Array_V_1_5_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_layer_in_row_Array_V_1_5_we0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_layer_in_row_Array_V_1_6_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_layer_in_row_Array_V_1_6_we0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_layer_in_row_Array_V_1_7_ce0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_layer_in_row_Array_V_1_7_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_address1);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_ce1);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_24_fu_450_p7 );
    sensitive << ( tmp_28_fu_576_p7 );
    sensitive << ( tmp_23_fu_630_p6 );
    sensitive << ( tmp_25_fu_695_p7 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_29_fu_729_p5 );

    SC_METHOD(thread_output_V_d1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_26_fu_516_p5 );
    sensitive << ( tmp_30_fu_652_p7 );
    sensitive << ( tmp_27_fu_707_p7 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_32_fu_739_p7 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_we1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_tmp_19_fu_416_p4);
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_tmp_21_fu_566_p4);
    sensitive << ( output_V_q0 );

    SC_METHOD(thread_tmp_23_fu_630_p6);
    sensitive << ( layer_in_row_Array_V_1_2_q0 );
    sensitive << ( reg_304 );
    sensitive << ( tmp_1_reg_830 );
    sensitive << ( trunc_ln203_1_reg_835 );
    sensitive << ( DataOut_V_10_reg_840 );

    SC_METHOD(thread_tmp_24_fu_450_p7);
    sensitive << ( layer_in_row_Array_V_1_3_q0 );
    sensitive << ( layer_in_row_Array_V_0_6_q0 );
    sensitive << ( trunc_ln203_fu_312_p1 );
    sensitive << ( grp_fu_254_p4 );
    sensitive << ( tmp_19_fu_416_p4 );
    sensitive << ( tmp_3_fu_440_p4 );

    SC_METHOD(thread_tmp_25_fu_695_p7);
    sensitive << ( layer_in_row_Array_V_1_4_q0 );
    sensitive << ( DataIn_V_assign_2_reg_769 );
    sensitive << ( tmp_22_reg_856 );
    sensitive << ( tmp_5_reg_861 );
    sensitive << ( tmp_6_reg_866 );
    sensitive << ( DataOut_V_14_reg_876 );

    SC_METHOD(thread_tmp_26_fu_516_p5);
    sensitive << ( layer_in_row_Array_V_1_5_q0 );
    sensitive << ( DataIn_V_assign_4_reg_775 );
    sensitive << ( grp_fu_254_p4 );
    sensitive << ( tmp_7_fu_506_p4 );

    SC_METHOD(thread_tmp_27_fu_707_p7);
    sensitive << ( layer_in_row_Array_V_1_6_q0 );
    sensitive << ( reg_308 );
    sensitive << ( DataIn_V_assign_6_reg_781 );
    sensitive << ( tmp_18_reg_892 );
    sensitive << ( tmp_10_reg_897 );
    sensitive << ( DataOut_V_1_reg_902 );

    SC_METHOD(thread_tmp_28_fu_576_p7);
    sensitive << ( layer_in_row_Array_V_0_1_q0 );
    sensitive << ( layer_in_row_Array_V_1_7_q0 );
    sensitive << ( grp_fu_244_p4 );
    sensitive << ( DataIn_V_assign_8_reg_791 );
    sensitive << ( grp_fu_264_p4 );
    sensitive << ( tmp_21_fu_566_p4 );

    SC_METHOD(thread_tmp_29_fu_729_p5);
    sensitive << ( reg_304 );
    sensitive << ( DataIn_V_assign_s_reg_797 );
    sensitive << ( DataOut_V_5_reg_907 );
    sensitive << ( tmp_14_reg_917 );

    SC_METHOD(thread_tmp_30_fu_652_p7);
    sensitive << ( layer_in_row_Array_V_1_0_q0 );
    sensitive << ( grp_fu_274_p4 );
    sensitive << ( DataOut_V_7_reg_786 );
    sensitive << ( DataIn_V_assign_1_reg_803 );
    sensitive << ( grp_fu_284_p4 );
    sensitive << ( grp_fu_294_p4 );

    SC_METHOD(thread_tmp_32_fu_739_p7);
    sensitive << ( layer_in_row_Array_V_1_1_q0 );
    sensitive << ( reg_308 );
    sensitive << ( DataIn_V_assign_3_reg_813 );
    sensitive << ( DataOut_V_9_reg_922 );
    sensitive << ( tmp_20_reg_927 );
    sensitive << ( tmp_31_reg_932 );

    SC_METHOD(thread_tmp_3_fu_440_p4);
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_tmp_7_fu_506_p4);
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_trunc_ln203_1_fu_436_p1);
    sensitive << ( output_V_q0 );

    SC_METHOD(thread_trunc_ln203_fu_312_p1);
    sensitive << ( ap_port_reg_data_V_read );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );

    SC_THREAD(thread_ap_var_for_const0);

    ap_CS_fsm = "0000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_V_read, "(port)data_V_read");
    sc_trace(mVcdFile, output_V_address0, "(port)output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "(port)output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "(port)output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "(port)output_V_d0");
    sc_trace(mVcdFile, output_V_q0, "(port)output_V_q0");
    sc_trace(mVcdFile, output_V_address1, "(port)output_V_address1");
    sc_trace(mVcdFile, output_V_ce1, "(port)output_V_ce1");
    sc_trace(mVcdFile, output_V_we1, "(port)output_V_we1");
    sc_trace(mVcdFile, output_V_d1, "(port)output_V_d1");
    sc_trace(mVcdFile, output_V_q1, "(port)output_V_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_0_ce0, "layer_in_row_Array_V_0_0_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_0_we0, "layer_in_row_Array_V_0_0_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_0_q0, "layer_in_row_Array_V_0_0_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_0_ce0, "layer_in_row_Array_V_1_0_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_0_we0, "layer_in_row_Array_V_1_0_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_0_q0, "layer_in_row_Array_V_1_0_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_1_ce0, "layer_in_row_Array_V_0_1_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_1_we0, "layer_in_row_Array_V_0_1_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_1_q0, "layer_in_row_Array_V_0_1_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_1_ce0, "layer_in_row_Array_V_1_1_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_1_we0, "layer_in_row_Array_V_1_1_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_1_q0, "layer_in_row_Array_V_1_1_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_2_ce0, "layer_in_row_Array_V_0_2_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_2_we0, "layer_in_row_Array_V_0_2_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_2_q0, "layer_in_row_Array_V_0_2_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_2_ce0, "layer_in_row_Array_V_1_2_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_2_we0, "layer_in_row_Array_V_1_2_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_2_q0, "layer_in_row_Array_V_1_2_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_3_ce0, "layer_in_row_Array_V_0_3_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_3_we0, "layer_in_row_Array_V_0_3_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_3_d0, "layer_in_row_Array_V_0_3_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_3_q0, "layer_in_row_Array_V_0_3_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_3_ce0, "layer_in_row_Array_V_1_3_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_3_we0, "layer_in_row_Array_V_1_3_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_3_q0, "layer_in_row_Array_V_1_3_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_4_ce0, "layer_in_row_Array_V_0_4_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_4_we0, "layer_in_row_Array_V_0_4_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_4_q0, "layer_in_row_Array_V_0_4_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_4_ce0, "layer_in_row_Array_V_1_4_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_4_we0, "layer_in_row_Array_V_1_4_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_4_q0, "layer_in_row_Array_V_1_4_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_5_ce0, "layer_in_row_Array_V_0_5_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_5_we0, "layer_in_row_Array_V_0_5_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_5_q0, "layer_in_row_Array_V_0_5_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_5_ce0, "layer_in_row_Array_V_1_5_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_5_we0, "layer_in_row_Array_V_1_5_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_5_q0, "layer_in_row_Array_V_1_5_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_6_ce0, "layer_in_row_Array_V_0_6_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_6_we0, "layer_in_row_Array_V_0_6_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_6_d0, "layer_in_row_Array_V_0_6_d0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_6_q0, "layer_in_row_Array_V_0_6_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_6_ce0, "layer_in_row_Array_V_1_6_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_6_we0, "layer_in_row_Array_V_1_6_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_6_q0, "layer_in_row_Array_V_1_6_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_7_ce0, "layer_in_row_Array_V_0_7_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_7_we0, "layer_in_row_Array_V_0_7_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_0_7_q0, "layer_in_row_Array_V_0_7_q0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_7_ce0, "layer_in_row_Array_V_1_7_ce0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_7_we0, "layer_in_row_Array_V_1_7_we0");
    sc_trace(mVcdFile, layer_in_row_Array_V_1_7_q0, "layer_in_row_Array_V_1_7_q0");
    sc_trace(mVcdFile, grp_fu_244_p4, "grp_fu_244_p4");
    sc_trace(mVcdFile, reg_304, "reg_304");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_fu_274_p4, "grp_fu_274_p4");
    sc_trace(mVcdFile, reg_308, "reg_308");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, trunc_ln203_fu_312_p1, "trunc_ln203_fu_312_p1");
    sc_trace(mVcdFile, trunc_ln203_reg_764, "trunc_ln203_reg_764");
    sc_trace(mVcdFile, DataIn_V_assign_2_reg_769, "DataIn_V_assign_2_reg_769");
    sc_trace(mVcdFile, DataIn_V_assign_4_reg_775, "DataIn_V_assign_4_reg_775");
    sc_trace(mVcdFile, DataIn_V_assign_6_reg_781, "DataIn_V_assign_6_reg_781");
    sc_trace(mVcdFile, DataOut_V_7_reg_786, "DataOut_V_7_reg_786");
    sc_trace(mVcdFile, DataIn_V_assign_8_reg_791, "DataIn_V_assign_8_reg_791");
    sc_trace(mVcdFile, DataIn_V_assign_s_reg_797, "DataIn_V_assign_s_reg_797");
    sc_trace(mVcdFile, DataIn_V_assign_1_reg_803, "DataIn_V_assign_1_reg_803");
    sc_trace(mVcdFile, DataOut_V_12_reg_808, "DataOut_V_12_reg_808");
    sc_trace(mVcdFile, DataIn_V_assign_3_reg_813, "DataIn_V_assign_3_reg_813");
    sc_trace(mVcdFile, tmp_1_reg_830, "tmp_1_reg_830");
    sc_trace(mVcdFile, trunc_ln203_1_fu_436_p1, "trunc_ln203_1_fu_436_p1");
    sc_trace(mVcdFile, trunc_ln203_1_reg_835, "trunc_ln203_1_reg_835");
    sc_trace(mVcdFile, DataOut_V_10_reg_840, "DataOut_V_10_reg_840");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_22_reg_856, "tmp_22_reg_856");
    sc_trace(mVcdFile, tmp_5_reg_861, "tmp_5_reg_861");
    sc_trace(mVcdFile, grp_fu_264_p4, "grp_fu_264_p4");
    sc_trace(mVcdFile, tmp_6_reg_866, "tmp_6_reg_866");
    sc_trace(mVcdFile, DataOut_V_3_reg_871, "DataOut_V_3_reg_871");
    sc_trace(mVcdFile, DataOut_V_14_reg_876, "DataOut_V_14_reg_876");
    sc_trace(mVcdFile, tmp_18_reg_892, "tmp_18_reg_892");
    sc_trace(mVcdFile, grp_fu_254_p4, "grp_fu_254_p4");
    sc_trace(mVcdFile, tmp_10_reg_897, "tmp_10_reg_897");
    sc_trace(mVcdFile, DataOut_V_1_reg_902, "DataOut_V_1_reg_902");
    sc_trace(mVcdFile, DataOut_V_5_reg_907, "DataOut_V_5_reg_907");
    sc_trace(mVcdFile, tmp_14_reg_917, "tmp_14_reg_917");
    sc_trace(mVcdFile, DataOut_V_9_reg_922, "DataOut_V_9_reg_922");
    sc_trace(mVcdFile, grp_fu_284_p4, "grp_fu_284_p4");
    sc_trace(mVcdFile, tmp_20_reg_927, "tmp_20_reg_927");
    sc_trace(mVcdFile, grp_fu_294_p4, "grp_fu_294_p4");
    sc_trace(mVcdFile, tmp_31_reg_932, "tmp_31_reg_932");
    sc_trace(mVcdFile, ap_port_reg_data_V_read, "ap_port_reg_data_V_read");
    sc_trace(mVcdFile, tmp_24_fu_450_p7, "tmp_24_fu_450_p7");
    sc_trace(mVcdFile, tmp_26_fu_516_p5, "tmp_26_fu_516_p5");
    sc_trace(mVcdFile, tmp_28_fu_576_p7, "tmp_28_fu_576_p7");
    sc_trace(mVcdFile, tmp_23_fu_630_p6, "tmp_23_fu_630_p6");
    sc_trace(mVcdFile, tmp_30_fu_652_p7, "tmp_30_fu_652_p7");
    sc_trace(mVcdFile, tmp_25_fu_695_p7, "tmp_25_fu_695_p7");
    sc_trace(mVcdFile, tmp_27_fu_707_p7, "tmp_27_fu_707_p7");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_29_fu_729_p5, "tmp_29_fu_729_p5");
    sc_trace(mVcdFile, tmp_32_fu_739_p7, "tmp_32_fu_739_p7");
    sc_trace(mVcdFile, tmp_19_fu_416_p4, "tmp_19_fu_416_p4");
    sc_trace(mVcdFile, tmp_3_fu_440_p4, "tmp_3_fu_440_p4");
    sc_trace(mVcdFile, tmp_7_fu_506_p4, "tmp_7_fu_506_p4");
    sc_trace(mVcdFile, tmp_21_fu_566_p4, "tmp_21_fu_566_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::~cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete layer_in_row_Array_V_0_0_U;
    delete layer_in_row_Array_V_1_0_U;
    delete layer_in_row_Array_V_0_1_U;
    delete layer_in_row_Array_V_1_1_U;
    delete layer_in_row_Array_V_0_2_U;
    delete layer_in_row_Array_V_1_2_U;
    delete layer_in_row_Array_V_0_3_U;
    delete layer_in_row_Array_V_1_3_U;
    delete layer_in_row_Array_V_0_4_U;
    delete layer_in_row_Array_V_1_4_U;
    delete layer_in_row_Array_V_0_5_U;
    delete layer_in_row_Array_V_1_5_U;
    delete layer_in_row_Array_V_0_6_U;
    delete layer_in_row_Array_V_1_6_U;
    delete layer_in_row_Array_V_0_7_U;
    delete layer_in_row_Array_V_1_7_U;
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv3_4;
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        DataIn_V_assign_1_reg_803 = ap_port_reg_data_V_read.read().range(111, 96);
        DataIn_V_assign_2_reg_769 = ap_port_reg_data_V_read.read().range(31, 16);
        DataIn_V_assign_3_reg_813 = ap_port_reg_data_V_read.read().range(127, 112);
        DataIn_V_assign_4_reg_775 = ap_port_reg_data_V_read.read().range(47, 32);
        DataIn_V_assign_6_reg_781 = ap_port_reg_data_V_read.read().range(63, 48);
        DataIn_V_assign_8_reg_791 = ap_port_reg_data_V_read.read().range(79, 64);
        DataIn_V_assign_s_reg_797 = ap_port_reg_data_V_read.read().range(95, 80);
        DataOut_V_12_reg_808 = layer_in_row_Array_V_0_6_q0.read();
        DataOut_V_7_reg_786 = layer_in_row_Array_V_0_3_q0.read();
        tmp_1_reg_830 = output_V_q0.read().range(79, 48);
        trunc_ln203_1_reg_835 = trunc_ln203_1_fu_436_p1.read();
        trunc_ln203_reg_764 = trunc_ln203_fu_312_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        DataOut_V_10_reg_840 = layer_in_row_Array_V_0_5_q0.read();
        tmp_22_reg_856 = output_V_q0.read().range(127, 112);
        tmp_5_reg_861 = output_V_q0.read().range(95, 64);
        tmp_6_reg_866 = output_V_q0.read().range(47, 16);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        DataOut_V_14_reg_876 = layer_in_row_Array_V_0_7_q0.read();
        DataOut_V_3_reg_871 = layer_in_row_Array_V_0_1_q0.read();
        tmp_10_reg_897 = output_V_q1.read().range(47, 16);
        tmp_18_reg_892 = output_V_q1.read().range(79, 64);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        DataOut_V_1_reg_902 = layer_in_row_Array_V_0_0_q0.read();
        DataOut_V_5_reg_907 = layer_in_row_Array_V_0_2_q0.read();
        tmp_14_reg_917 = output_V_q0.read().range(79, 16);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        DataOut_V_9_reg_922 = layer_in_row_Array_V_0_4_q0.read();
        tmp_20_reg_927 = output_V_q1.read().range(31, 16);
        tmp_31_reg_932 = output_V_q1.read().range(79, 48);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        ap_port_reg_data_V_read = data_V_read.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        reg_304 = output_V_q0.read().range(127, 96);
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        reg_308 = output_V_q1.read().range(127, 96);
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_grp_fu_244_p4() {
    grp_fu_244_p4 = output_V_q0.read().range(127, 96);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_grp_fu_254_p4() {
    grp_fu_254_p4 = output_V_q1.read().range(47, 16);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_grp_fu_264_p4() {
    grp_fu_264_p4 = output_V_q0.read().range(47, 16);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_grp_fu_274_p4() {
    grp_fu_274_p4 = output_V_q1.read().range(127, 96);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_grp_fu_284_p4() {
    grp_fu_284_p4 = output_V_q1.read().range(31, 16);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_grp_fu_294_p4() {
    grp_fu_294_p4 = output_V_q1.read().range(79, 48);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        layer_in_row_Array_V_0_0_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_0_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        layer_in_row_Array_V_0_0_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_0_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_row_Array_V_0_1_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_1_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_row_Array_V_0_1_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_1_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        layer_in_row_Array_V_0_2_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_2_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        layer_in_row_Array_V_0_2_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_2_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        layer_in_row_Array_V_0_3_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_3_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_3_d0() {
    layer_in_row_Array_V_0_3_d0 = ap_port_reg_data_V_read.read().range(63, 48);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_3_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        layer_in_row_Array_V_0_3_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_3_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        layer_in_row_Array_V_0_4_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_4_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_4_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        layer_in_row_Array_V_0_4_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_4_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        layer_in_row_Array_V_0_5_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_5_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_5_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        layer_in_row_Array_V_0_5_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_5_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        layer_in_row_Array_V_0_6_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_6_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_6_d0() {
    layer_in_row_Array_V_0_6_d0 = ap_port_reg_data_V_read.read().range(111, 96);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_6_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        layer_in_row_Array_V_0_6_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_6_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_row_Array_V_0_7_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_7_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_0_7_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_row_Array_V_0_7_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_0_7_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        layer_in_row_Array_V_1_0_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_0_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_0_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        layer_in_row_Array_V_1_0_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_0_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        layer_in_row_Array_V_1_1_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_1_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_1_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        layer_in_row_Array_V_1_1_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_1_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        layer_in_row_Array_V_1_2_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_2_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_2_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        layer_in_row_Array_V_1_2_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_2_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        layer_in_row_Array_V_1_3_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_3_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_3_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        layer_in_row_Array_V_1_3_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_3_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_4_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        layer_in_row_Array_V_1_4_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_4_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_4_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        layer_in_row_Array_V_1_4_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_4_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_5_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        layer_in_row_Array_V_1_5_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_5_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_5_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        layer_in_row_Array_V_1_5_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_5_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_6_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        layer_in_row_Array_V_1_6_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_6_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_6_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        layer_in_row_Array_V_1_6_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_6_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_7_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_row_Array_V_1_7_ce0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_7_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_layer_in_row_Array_V_1_7_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        layer_in_row_Array_V_1_7_we0 =  (sc_logic) (ap_const_lv1_1[0]);
    } else {
        layer_in_row_Array_V_1_7_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_output_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_address0 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_address0 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_address0 =  (sc_lv<4>) (ap_const_lv64_5);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_V_address0 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_V_address0 =  (sc_lv<4>) (ap_const_lv64_1);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        output_V_address0 =  (sc_lv<4>) (ap_const_lv64_8);
    } else {
        output_V_address0 = "XXXX";
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_output_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_address1 =  (sc_lv<4>) (ap_const_lv64_8);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_address1 =  (sc_lv<4>) (ap_const_lv64_4);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_address1 =  (sc_lv<4>) (ap_const_lv64_7);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_address1 =  (sc_lv<4>) (ap_const_lv64_6);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_V_address1 =  (sc_lv<4>) (ap_const_lv64_3);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_V_address1 =  (sc_lv<4>) (ap_const_lv64_2);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        output_V_address1 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        output_V_address1 = "XXXX";
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_output_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_output_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1)) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_V_ce1 = ap_const_logic_1;
    } else {
        output_V_ce1 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_output_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_d0 = tmp_29_fu_729_p5.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_d0 = tmp_25_fu_695_p7.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_d0 = tmp_23_fu_630_p6.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_d0 = tmp_28_fu_576_p7.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        output_V_d0 = tmp_24_fu_450_p7.read();
    } else {
        output_V_d0 =  (sc_lv<128>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_output_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_d1 = tmp_32_fu_739_p7.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_d1 = tmp_27_fu_707_p7.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_d1 = tmp_30_fu_652_p7.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_V_d1 = tmp_26_fu_516_p5.read();
    } else {
        output_V_d1 =  (sc_lv<128>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_output_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_output_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_V_we1 = ap_const_logic_1;
    } else {
        output_V_we1 = ap_const_logic_0;
    }
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_19_fu_416_p4() {
    tmp_19_fu_416_p4 = output_V_q1.read().range(127, 112);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_21_fu_566_p4() {
    tmp_21_fu_566_p4 = output_V_q0.read().range(79, 64);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_23_fu_630_p6() {
    tmp_23_fu_630_p6 = esl_concat<96,32>(esl_concat<80,16>(esl_concat<48,32>(esl_concat<32,16>(reg_304.read(), DataOut_V_10_reg_840.read()), tmp_1_reg_830.read()), layer_in_row_Array_V_1_2_q0.read()), trunc_ln203_1_reg_835.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_24_fu_450_p7() {
    tmp_24_fu_450_p7 = esl_concat<96,32>(esl_concat<80,16>(esl_concat<48,32>(esl_concat<32,16>(esl_concat<16,16>(trunc_ln203_fu_312_p1.read(), tmp_19_fu_416_p4.read()), layer_in_row_Array_V_0_6_q0.read()), tmp_3_fu_440_p4.read()), layer_in_row_Array_V_1_3_q0.read()), grp_fu_254_p4.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_25_fu_695_p7() {
    tmp_25_fu_695_p7 = esl_concat<96,32>(esl_concat<80,16>(esl_concat<48,32>(esl_concat<32,16>(esl_concat<16,16>(DataIn_V_assign_2_reg_769.read(), tmp_22_reg_856.read()), DataOut_V_14_reg_876.read()), tmp_5_reg_861.read()), layer_in_row_Array_V_1_4_q0.read()), tmp_6_reg_866.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_26_fu_516_p5() {
    tmp_26_fu_516_p5 = esl_concat<96,32>(esl_concat<80,16>(esl_concat<16,64>(DataIn_V_assign_4_reg_775.read(), tmp_7_fu_506_p4.read()), layer_in_row_Array_V_1_5_q0.read()), grp_fu_254_p4.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_27_fu_707_p7() {
    tmp_27_fu_707_p7 = esl_concat<96,32>(esl_concat<80,16>(esl_concat<64,16>(esl_concat<48,16>(esl_concat<16,32>(DataIn_V_assign_6_reg_781.read(), reg_308.read()), DataOut_V_1_reg_902.read()), tmp_18_reg_892.read()), layer_in_row_Array_V_1_6_q0.read()), tmp_10_reg_897.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_28_fu_576_p7() {
    tmp_28_fu_576_p7 = esl_concat<96,32>(esl_concat<80,16>(esl_concat<64,16>(esl_concat<48,16>(esl_concat<16,32>(DataIn_V_assign_8_reg_791.read(), grp_fu_244_p4.read()), layer_in_row_Array_V_0_1_q0.read()), tmp_21_fu_566_p4.read()), layer_in_row_Array_V_1_7_q0.read()), grp_fu_264_p4.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_29_fu_729_p5() {
    tmp_29_fu_729_p5 = esl_concat<64,64>(esl_concat<48,16>(esl_concat<16,32>(DataIn_V_assign_s_reg_797.read(), reg_304.read()), DataOut_V_5_reg_907.read()), tmp_14_reg_917.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_30_fu_652_p7() {
    tmp_30_fu_652_p7 = esl_concat<112,16>(esl_concat<96,16>(esl_concat<64,32>(esl_concat<48,16>(esl_concat<16,32>(DataIn_V_assign_1_reg_803.read(), grp_fu_274_p4.read()), DataOut_V_7_reg_786.read()), grp_fu_294_p4.read()), layer_in_row_Array_V_1_0_q0.read()), grp_fu_284_p4.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_32_fu_739_p7() {
    tmp_32_fu_739_p7 = esl_concat<112,16>(esl_concat<96,16>(esl_concat<64,32>(esl_concat<48,16>(esl_concat<16,32>(DataIn_V_assign_3_reg_813.read(), reg_308.read()), DataOut_V_9_reg_922.read()), tmp_31_reg_932.read()), layer_in_row_Array_V_1_1_q0.read()), tmp_20_reg_927.read());
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_3_fu_440_p4() {
    tmp_3_fu_440_p4 = output_V_q1.read().range(95, 64);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_tmp_7_fu_506_p4() {
    tmp_7_fu_506_p4 = output_V_q1.read().range(127, 64);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_trunc_ln203_1_fu_436_p1() {
    trunc_ln203_1_fu_436_p1 = output_V_q0.read().range(32-1, 0);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_trunc_ln203_fu_312_p1() {
    trunc_ln203_fu_312_p1 = ap_port_reg_data_V_read.read().range(16-1, 0);
}

void cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<7>) ("XXXXXXX");
            break;
    }
}

}

