// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_HH_
#define _cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb.h"

namespace ap_rtl {

struct cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s : public sc_module {
    // Port declarations 17
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_in< sc_lv<128> > data_V_read;
    sc_out< sc_lv<4> > output_V_address0;
    sc_out< sc_logic > output_V_ce0;
    sc_out< sc_logic > output_V_we0;
    sc_out< sc_lv<128> > output_V_d0;
    sc_in< sc_lv<128> > output_V_q0;
    sc_out< sc_lv<4> > output_V_address1;
    sc_out< sc_logic > output_V_ce1;
    sc_out< sc_logic > output_V_we1;
    sc_out< sc_lv<128> > output_V_d1;
    sc_in< sc_lv<128> > output_V_q1;
    sc_signal< sc_lv<3> > ap_var_for_const0;


    // Module declarations
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s(sc_module_name name);
    SC_HAS_PROCESS(cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s);

    ~cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s();

    sc_trace_file* mVcdFile;

    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_0_0_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_1_0_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_0_1_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_1_1_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_0_2_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_1_2_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_0_3_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_1_3_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_0_4_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_1_4_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_0_5_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_1_5_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_0_6_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_1_6_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_0_7_U;
    cnnshift_arr_ap_fixed_ap_fixed_16_14_5_3_0_config2_s_layebkb* layer_in_row_Array_V_1_7_U;
    sc_signal< sc_lv<7> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > layer_in_row_Array_V_0_0_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_0_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_0_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_0_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_0_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_1_0_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_1_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_1_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_1_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_1_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_1_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_1_1_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_2_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_2_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_2_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_2_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_2_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_1_2_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_3_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_3_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_3_d0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_3_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_3_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_3_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_1_3_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_4_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_4_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_4_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_4_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_4_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_1_4_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_5_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_5_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_5_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_5_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_5_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_1_5_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_6_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_6_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_6_d0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_6_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_6_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_6_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_1_6_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_7_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_0_7_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_0_7_q0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_7_ce0;
    sc_signal< sc_logic > layer_in_row_Array_V_1_7_we0;
    sc_signal< sc_lv<16> > layer_in_row_Array_V_1_7_q0;
    sc_signal< sc_lv<32> > grp_fu_244_p4;
    sc_signal< sc_lv<32> > reg_304;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > grp_fu_274_p4;
    sc_signal< sc_lv<32> > reg_308;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<16> > trunc_ln203_fu_312_p1;
    sc_signal< sc_lv<16> > trunc_ln203_reg_764;
    sc_signal< sc_lv<16> > DataIn_V_assign_2_reg_769;
    sc_signal< sc_lv<16> > DataIn_V_assign_4_reg_775;
    sc_signal< sc_lv<16> > DataIn_V_assign_6_reg_781;
    sc_signal< sc_lv<16> > DataOut_V_7_reg_786;
    sc_signal< sc_lv<16> > DataIn_V_assign_8_reg_791;
    sc_signal< sc_lv<16> > DataIn_V_assign_s_reg_797;
    sc_signal< sc_lv<16> > DataIn_V_assign_1_reg_803;
    sc_signal< sc_lv<16> > DataOut_V_12_reg_808;
    sc_signal< sc_lv<16> > DataIn_V_assign_3_reg_813;
    sc_signal< sc_lv<32> > tmp_1_reg_830;
    sc_signal< sc_lv<32> > trunc_ln203_1_fu_436_p1;
    sc_signal< sc_lv<32> > trunc_ln203_1_reg_835;
    sc_signal< sc_lv<16> > DataOut_V_10_reg_840;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<16> > tmp_22_reg_856;
    sc_signal< sc_lv<32> > tmp_5_reg_861;
    sc_signal< sc_lv<32> > grp_fu_264_p4;
    sc_signal< sc_lv<32> > tmp_6_reg_866;
    sc_signal< sc_lv<16> > DataOut_V_3_reg_871;
    sc_signal< sc_lv<16> > DataOut_V_14_reg_876;
    sc_signal< sc_lv<16> > tmp_18_reg_892;
    sc_signal< sc_lv<32> > grp_fu_254_p4;
    sc_signal< sc_lv<32> > tmp_10_reg_897;
    sc_signal< sc_lv<16> > DataOut_V_1_reg_902;
    sc_signal< sc_lv<16> > DataOut_V_5_reg_907;
    sc_signal< sc_lv<64> > tmp_14_reg_917;
    sc_signal< sc_lv<16> > DataOut_V_9_reg_922;
    sc_signal< sc_lv<16> > grp_fu_284_p4;
    sc_signal< sc_lv<16> > tmp_20_reg_927;
    sc_signal< sc_lv<32> > grp_fu_294_p4;
    sc_signal< sc_lv<32> > tmp_31_reg_932;
    sc_signal< sc_lv<128> > ap_port_reg_data_V_read;
    sc_signal< sc_lv<128> > tmp_24_fu_450_p7;
    sc_signal< sc_lv<128> > tmp_26_fu_516_p5;
    sc_signal< sc_lv<128> > tmp_28_fu_576_p7;
    sc_signal< sc_lv<128> > tmp_23_fu_630_p6;
    sc_signal< sc_lv<128> > tmp_30_fu_652_p7;
    sc_signal< sc_lv<128> > tmp_25_fu_695_p7;
    sc_signal< sc_lv<128> > tmp_27_fu_707_p7;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<128> > tmp_29_fu_729_p5;
    sc_signal< sc_lv<128> > tmp_32_fu_739_p7;
    sc_signal< sc_lv<16> > tmp_19_fu_416_p4;
    sc_signal< sc_lv<32> > tmp_3_fu_440_p4;
    sc_signal< sc_lv<64> > tmp_7_fu_506_p4;
    sc_signal< sc_lv<16> > tmp_21_fu_566_p4;
    sc_signal< sc_lv<7> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<7> ap_ST_fsm_state1;
    static const sc_lv<7> ap_ST_fsm_state2;
    static const sc_lv<7> ap_ST_fsm_state3;
    static const sc_lv<7> ap_ST_fsm_state4;
    static const sc_lv<7> ap_ST_fsm_state5;
    static const sc_lv<7> ap_ST_fsm_state6;
    static const sc_lv<7> ap_ST_fsm_state7;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<64> ap_const_lv64_8;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<64> ap_const_lv64_5;
    static const sc_lv<64> ap_const_lv64_6;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<32> ap_const_lv32_60;
    static const sc_lv<32> ap_const_lv32_7F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_2F;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<32> ap_const_lv32_30;
    static const sc_lv<32> ap_const_lv32_4F;
    static const sc_lv<32> ap_const_lv32_20;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_40;
    static const sc_lv<32> ap_const_lv32_50;
    static const sc_lv<32> ap_const_lv32_5F;
    static const sc_lv<32> ap_const_lv32_6F;
    static const sc_lv<32> ap_const_lv32_70;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_fu_244_p4();
    void thread_grp_fu_254_p4();
    void thread_grp_fu_264_p4();
    void thread_grp_fu_274_p4();
    void thread_grp_fu_284_p4();
    void thread_grp_fu_294_p4();
    void thread_layer_in_row_Array_V_0_0_ce0();
    void thread_layer_in_row_Array_V_0_0_we0();
    void thread_layer_in_row_Array_V_0_1_ce0();
    void thread_layer_in_row_Array_V_0_1_we0();
    void thread_layer_in_row_Array_V_0_2_ce0();
    void thread_layer_in_row_Array_V_0_2_we0();
    void thread_layer_in_row_Array_V_0_3_ce0();
    void thread_layer_in_row_Array_V_0_3_d0();
    void thread_layer_in_row_Array_V_0_3_we0();
    void thread_layer_in_row_Array_V_0_4_ce0();
    void thread_layer_in_row_Array_V_0_4_we0();
    void thread_layer_in_row_Array_V_0_5_ce0();
    void thread_layer_in_row_Array_V_0_5_we0();
    void thread_layer_in_row_Array_V_0_6_ce0();
    void thread_layer_in_row_Array_V_0_6_d0();
    void thread_layer_in_row_Array_V_0_6_we0();
    void thread_layer_in_row_Array_V_0_7_ce0();
    void thread_layer_in_row_Array_V_0_7_we0();
    void thread_layer_in_row_Array_V_1_0_ce0();
    void thread_layer_in_row_Array_V_1_0_we0();
    void thread_layer_in_row_Array_V_1_1_ce0();
    void thread_layer_in_row_Array_V_1_1_we0();
    void thread_layer_in_row_Array_V_1_2_ce0();
    void thread_layer_in_row_Array_V_1_2_we0();
    void thread_layer_in_row_Array_V_1_3_ce0();
    void thread_layer_in_row_Array_V_1_3_we0();
    void thread_layer_in_row_Array_V_1_4_ce0();
    void thread_layer_in_row_Array_V_1_4_we0();
    void thread_layer_in_row_Array_V_1_5_ce0();
    void thread_layer_in_row_Array_V_1_5_we0();
    void thread_layer_in_row_Array_V_1_6_ce0();
    void thread_layer_in_row_Array_V_1_6_we0();
    void thread_layer_in_row_Array_V_1_7_ce0();
    void thread_layer_in_row_Array_V_1_7_we0();
    void thread_output_V_address0();
    void thread_output_V_address1();
    void thread_output_V_ce0();
    void thread_output_V_ce1();
    void thread_output_V_d0();
    void thread_output_V_d1();
    void thread_output_V_we0();
    void thread_output_V_we1();
    void thread_tmp_19_fu_416_p4();
    void thread_tmp_21_fu_566_p4();
    void thread_tmp_23_fu_630_p6();
    void thread_tmp_24_fu_450_p7();
    void thread_tmp_25_fu_695_p7();
    void thread_tmp_26_fu_516_p5();
    void thread_tmp_27_fu_707_p7();
    void thread_tmp_28_fu_576_p7();
    void thread_tmp_29_fu_729_p5();
    void thread_tmp_30_fu_652_p7();
    void thread_tmp_32_fu_739_p7();
    void thread_tmp_3_fu_440_p4();
    void thread_tmp_7_fu_506_p4();
    void thread_trunc_ln203_1_fu_436_p1();
    void thread_trunc_ln203_fu_312_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
