// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "relu_array_ap_fixed_ap_fixed_relu_config55_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_ST_fsm_state1 = "1";
const sc_lv<3> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<3> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_ST_fsm_state5 = "100";
const sc_lv<32> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_boolean_1 = true;
const sc_lv<32> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv32_1 = "1";
const bool relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_boolean_0 = false;
const sc_lv<1> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv1_0 = "0";
const sc_lv<1> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv1_1 = "1";
const sc_lv<10> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv10_0 = "0000000000";
const sc_lv<10> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv10_268 = "1001101000";
const sc_lv<10> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv10_1 = "1";
const sc_lv<16> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv16_0 = "0000000000000000";
const sc_lv<15> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv15_0 = "000000000000000";
const sc_lv<32> relu_array_ap_fixed_ap_fixed_relu_config55_s::ap_const_lv32_2 = "10";

relu_array_ap_fixed_ap_fixed_relu_config55_s::relu_array_ap_fixed_ap_fixed_relu_config55_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    regslice_both_data_0_V_V_U = new regslice_both<16>("regslice_both_data_0_V_V_U");
    regslice_both_data_0_V_V_U->ap_clk(ap_clk);
    regslice_both_data_0_V_V_U->ap_rst(ap_rst);
    regslice_both_data_0_V_V_U->data_in(data_0_V_V_TDATA);
    regslice_both_data_0_V_V_U->vld_in(data_0_V_V_TVALID);
    regslice_both_data_0_V_V_U->ack_in(regslice_both_data_0_V_V_U_ack_in);
    regslice_both_data_0_V_V_U->data_out(data_0_V_V_TDATA_int);
    regslice_both_data_0_V_V_U->vld_out(data_0_V_V_TVALID_int);
    regslice_both_data_0_V_V_U->ack_out(data_0_V_V_TREADY_int);
    regslice_both_data_0_V_V_U->apdone_blk(regslice_both_data_0_V_V_U_apdone_blk);
    regslice_both_data_1_V_V_U = new regslice_both<16>("regslice_both_data_1_V_V_U");
    regslice_both_data_1_V_V_U->ap_clk(ap_clk);
    regslice_both_data_1_V_V_U->ap_rst(ap_rst);
    regslice_both_data_1_V_V_U->data_in(data_1_V_V_TDATA);
    regslice_both_data_1_V_V_U->vld_in(data_1_V_V_TVALID);
    regslice_both_data_1_V_V_U->ack_in(regslice_both_data_1_V_V_U_ack_in);
    regslice_both_data_1_V_V_U->data_out(data_1_V_V_TDATA_int);
    regslice_both_data_1_V_V_U->vld_out(data_1_V_V_TVALID_int);
    regslice_both_data_1_V_V_U->ack_out(data_1_V_V_TREADY_int);
    regslice_both_data_1_V_V_U->apdone_blk(regslice_both_data_1_V_V_U_apdone_blk);
    regslice_both_data_2_V_V_U = new regslice_both<16>("regslice_both_data_2_V_V_U");
    regslice_both_data_2_V_V_U->ap_clk(ap_clk);
    regslice_both_data_2_V_V_U->ap_rst(ap_rst);
    regslice_both_data_2_V_V_U->data_in(data_2_V_V_TDATA);
    regslice_both_data_2_V_V_U->vld_in(data_2_V_V_TVALID);
    regslice_both_data_2_V_V_U->ack_in(regslice_both_data_2_V_V_U_ack_in);
    regslice_both_data_2_V_V_U->data_out(data_2_V_V_TDATA_int);
    regslice_both_data_2_V_V_U->vld_out(data_2_V_V_TVALID_int);
    regslice_both_data_2_V_V_U->ack_out(data_2_V_V_TREADY_int);
    regslice_both_data_2_V_V_U->apdone_blk(regslice_both_data_2_V_V_U_apdone_blk);
    regslice_both_data_3_V_V_U = new regslice_both<16>("regslice_both_data_3_V_V_U");
    regslice_both_data_3_V_V_U->ap_clk(ap_clk);
    regslice_both_data_3_V_V_U->ap_rst(ap_rst);
    regslice_both_data_3_V_V_U->data_in(data_3_V_V_TDATA);
    regslice_both_data_3_V_V_U->vld_in(data_3_V_V_TVALID);
    regslice_both_data_3_V_V_U->ack_in(regslice_both_data_3_V_V_U_ack_in);
    regslice_both_data_3_V_V_U->data_out(data_3_V_V_TDATA_int);
    regslice_both_data_3_V_V_U->vld_out(data_3_V_V_TVALID_int);
    regslice_both_data_3_V_V_U->ack_out(data_3_V_V_TREADY_int);
    regslice_both_data_3_V_V_U->apdone_blk(regslice_both_data_3_V_V_U_apdone_blk);
    regslice_both_res_0_V_V_U = new regslice_both<16>("regslice_both_res_0_V_V_U");
    regslice_both_res_0_V_V_U->ap_clk(ap_clk);
    regslice_both_res_0_V_V_U->ap_rst(ap_rst);
    regslice_both_res_0_V_V_U->data_in(res_0_V_V_TDATA_int);
    regslice_both_res_0_V_V_U->vld_in(res_0_V_V_TVALID_int);
    regslice_both_res_0_V_V_U->ack_in(res_0_V_V_TREADY_int);
    regslice_both_res_0_V_V_U->data_out(res_0_V_V_TDATA);
    regslice_both_res_0_V_V_U->vld_out(regslice_both_res_0_V_V_U_vld_out);
    regslice_both_res_0_V_V_U->ack_out(res_0_V_V_TREADY);
    regslice_both_res_0_V_V_U->apdone_blk(regslice_both_res_0_V_V_U_apdone_blk);
    regslice_both_res_1_V_V_U = new regslice_both<16>("regslice_both_res_1_V_V_U");
    regslice_both_res_1_V_V_U->ap_clk(ap_clk);
    regslice_both_res_1_V_V_U->ap_rst(ap_rst);
    regslice_both_res_1_V_V_U->data_in(res_1_V_V_TDATA_int);
    regslice_both_res_1_V_V_U->vld_in(res_1_V_V_TVALID_int);
    regslice_both_res_1_V_V_U->ack_in(res_1_V_V_TREADY_int);
    regslice_both_res_1_V_V_U->data_out(res_1_V_V_TDATA);
    regslice_both_res_1_V_V_U->vld_out(regslice_both_res_1_V_V_U_vld_out);
    regslice_both_res_1_V_V_U->ack_out(res_1_V_V_TREADY);
    regslice_both_res_1_V_V_U->apdone_blk(regslice_both_res_1_V_V_U_apdone_blk);
    regslice_both_res_2_V_V_U = new regslice_both<16>("regslice_both_res_2_V_V_U");
    regslice_both_res_2_V_V_U->ap_clk(ap_clk);
    regslice_both_res_2_V_V_U->ap_rst(ap_rst);
    regslice_both_res_2_V_V_U->data_in(res_2_V_V_TDATA_int);
    regslice_both_res_2_V_V_U->vld_in(res_2_V_V_TVALID_int);
    regslice_both_res_2_V_V_U->ack_in(res_2_V_V_TREADY_int);
    regslice_both_res_2_V_V_U->data_out(res_2_V_V_TDATA);
    regslice_both_res_2_V_V_U->vld_out(regslice_both_res_2_V_V_U_vld_out);
    regslice_both_res_2_V_V_U->ack_out(res_2_V_V_TREADY);
    regslice_both_res_2_V_V_U->apdone_blk(regslice_both_res_2_V_V_U_apdone_blk);
    regslice_both_res_3_V_V_U = new regslice_both<16>("regslice_both_res_3_V_V_U");
    regslice_both_res_3_V_V_U->ap_clk(ap_clk);
    regslice_both_res_3_V_V_U->ap_rst(ap_rst);
    regslice_both_res_3_V_V_U->data_in(res_3_V_V_TDATA_int);
    regslice_both_res_3_V_V_U->vld_in(res_3_V_V_TVALID_int);
    regslice_both_res_3_V_V_U->ack_in(res_3_V_V_TREADY_int);
    regslice_both_res_3_V_V_U->data_out(res_3_V_V_TDATA);
    regslice_both_res_3_V_V_U->vld_out(regslice_both_res_3_V_V_U_vld_out);
    regslice_both_res_3_V_V_U->ack_out(res_3_V_V_TREADY);
    regslice_both_res_3_V_V_U->apdone_blk(regslice_both_res_3_V_V_U_apdone_blk);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( data_0_V_V_TVALID_int );
    sensitive << ( data_1_V_V_TVALID_int );
    sensitive << ( data_2_V_V_TVALID_int );
    sensitive << ( data_3_V_V_TVALID_int );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_block_state4_io );
    sensitive << ( data_0_V_V_TVALID_int );
    sensitive << ( data_1_V_V_TVALID_int );
    sensitive << ( data_2_V_V_TVALID_int );
    sensitive << ( data_3_V_V_TVALID_int );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_state3_io );
    sensitive << ( ap_block_state4_io );
    sensitive << ( data_0_V_V_TVALID_int );
    sensitive << ( data_1_V_V_TVALID_int );
    sensitive << ( data_2_V_V_TVALID_int );
    sensitive << ( data_3_V_V_TVALID_int );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( data_0_V_V_TVALID_int );
    sensitive << ( data_1_V_V_TVALID_int );
    sensitive << ( data_2_V_V_TVALID_int );
    sensitive << ( data_3_V_V_TVALID_int );

    SC_METHOD(thread_ap_block_state3_io);
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( res_0_V_V_TREADY_int );
    sensitive << ( res_1_V_V_TREADY_int );
    sensitive << ( res_2_V_V_TREADY_int );
    sensitive << ( res_3_V_V_TREADY_int );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state4_io);
    sensitive << ( icmp_ln79_reg_221_pp0_iter1_reg );
    sensitive << ( res_0_V_V_TREADY_int );
    sensitive << ( res_1_V_V_TREADY_int );
    sensitive << ( res_2_V_V_TREADY_int );
    sensitive << ( res_3_V_V_TREADY_int );

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state5);
    sensitive << ( regslice_both_res_0_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_1_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_2_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_3_V_V_U_apdone_blk );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( icmp_ln79_fu_121_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( regslice_both_res_0_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_1_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_2_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_3_V_V_U_apdone_blk );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( regslice_both_res_0_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_1_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_2_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_3_V_V_U_apdone_blk );

    SC_METHOD(thread_data_0_V_V_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( data_0_V_V_TVALID_int );

    SC_METHOD(thread_data_0_V_V_TREADY);
    sensitive << ( data_0_V_V_TVALID );
    sensitive << ( regslice_both_data_0_V_V_U_ack_in );

    SC_METHOD(thread_data_0_V_V_TREADY_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_1_V_V_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( data_1_V_V_TVALID_int );

    SC_METHOD(thread_data_1_V_V_TREADY);
    sensitive << ( data_1_V_V_TVALID );
    sensitive << ( regslice_both_data_1_V_V_U_ack_in );

    SC_METHOD(thread_data_1_V_V_TREADY_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_2_V_V_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( data_2_V_V_TVALID_int );

    SC_METHOD(thread_data_2_V_V_TREADY);
    sensitive << ( data_2_V_V_TVALID );
    sensitive << ( regslice_both_data_2_V_V_U_ack_in );

    SC_METHOD(thread_data_2_V_V_TREADY_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_data_3_V_V_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( data_3_V_V_TVALID_int );

    SC_METHOD(thread_data_3_V_V_TREADY);
    sensitive << ( data_3_V_V_TVALID );
    sensitive << ( regslice_both_data_3_V_V_U_ack_in );

    SC_METHOD(thread_data_3_V_V_TREADY_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_i_fu_127_p2);
    sensitive << ( i_0_reg_110 );

    SC_METHOD(thread_icmp_ln1494_1_fu_163_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( data_1_V_V_TDATA_int );

    SC_METHOD(thread_icmp_ln1494_2_fu_177_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( data_2_V_V_TDATA_int );

    SC_METHOD(thread_icmp_ln1494_3_fu_191_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( data_3_V_V_TDATA_int );

    SC_METHOD(thread_icmp_ln1494_fu_149_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( data_0_V_V_TDATA_int );

    SC_METHOD(thread_icmp_ln79_fu_121_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( i_0_reg_110 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_0_V_V_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln79_reg_221_pp0_iter1_reg );
    sensitive << ( res_0_V_V_TREADY_int );

    SC_METHOD(thread_res_0_V_V_TDATA_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( tmp_V_reg_230 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_0_V_V_TVALID);
    sensitive << ( regslice_both_res_0_V_V_U_vld_out );

    SC_METHOD(thread_res_0_V_V_TVALID_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_1_V_V_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln79_reg_221_pp0_iter1_reg );
    sensitive << ( res_1_V_V_TREADY_int );

    SC_METHOD(thread_res_1_V_V_TDATA_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( tmp_V_2_reg_235 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_1_V_V_TVALID);
    sensitive << ( regslice_both_res_1_V_V_U_vld_out );

    SC_METHOD(thread_res_1_V_V_TVALID_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_2_V_V_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln79_reg_221_pp0_iter1_reg );
    sensitive << ( res_2_V_V_TREADY_int );

    SC_METHOD(thread_res_2_V_V_TDATA_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( tmp_V_4_reg_240 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_2_V_V_TVALID);
    sensitive << ( regslice_both_res_2_V_V_U_vld_out );

    SC_METHOD(thread_res_2_V_V_TVALID_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_res_3_V_V_TDATA_blk_n);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( icmp_ln79_reg_221_pp0_iter1_reg );
    sensitive << ( res_3_V_V_TREADY_int );

    SC_METHOD(thread_res_3_V_V_TDATA_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( tmp_V_6_reg_245 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_res_3_V_V_TVALID);
    sensitive << ( regslice_both_res_3_V_V_U_vld_out );

    SC_METHOD(thread_res_3_V_V_TVALID_int);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( icmp_ln79_reg_221 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_tmp_V_2_fu_169_p3);
    sensitive << ( icmp_ln1494_1_fu_163_p2 );
    sensitive << ( trunc_ln203_1_fu_137_p1 );

    SC_METHOD(thread_tmp_V_4_fu_183_p3);
    sensitive << ( icmp_ln1494_2_fu_177_p2 );
    sensitive << ( trunc_ln203_2_fu_141_p1 );

    SC_METHOD(thread_tmp_V_6_fu_197_p3);
    sensitive << ( icmp_ln1494_3_fu_191_p2 );
    sensitive << ( trunc_ln203_3_fu_145_p1 );

    SC_METHOD(thread_tmp_V_fu_155_p3);
    sensitive << ( icmp_ln1494_fu_149_p2 );
    sensitive << ( trunc_ln203_fu_133_p1 );

    SC_METHOD(thread_trunc_ln203_1_fu_137_p1);
    sensitive << ( data_1_V_V_TDATA_int );

    SC_METHOD(thread_trunc_ln203_2_fu_141_p1);
    sensitive << ( data_2_V_V_TDATA_int );

    SC_METHOD(thread_trunc_ln203_3_fu_145_p1);
    sensitive << ( data_3_V_V_TDATA_int );

    SC_METHOD(thread_trunc_ln203_fu_133_p1);
    sensitive << ( data_0_V_V_TDATA_int );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( icmp_ln79_fu_121_p2 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( regslice_both_res_0_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_1_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_2_V_V_U_apdone_blk );
    sensitive << ( regslice_both_res_3_V_V_U_apdone_blk );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "relu_array_ap_fixed_ap_fixed_relu_config55_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, data_0_V_V_TDATA, "(port)data_0_V_V_TDATA");
    sc_trace(mVcdFile, data_0_V_V_TVALID, "(port)data_0_V_V_TVALID");
    sc_trace(mVcdFile, data_0_V_V_TREADY, "(port)data_0_V_V_TREADY");
    sc_trace(mVcdFile, data_1_V_V_TDATA, "(port)data_1_V_V_TDATA");
    sc_trace(mVcdFile, data_1_V_V_TVALID, "(port)data_1_V_V_TVALID");
    sc_trace(mVcdFile, data_1_V_V_TREADY, "(port)data_1_V_V_TREADY");
    sc_trace(mVcdFile, data_2_V_V_TDATA, "(port)data_2_V_V_TDATA");
    sc_trace(mVcdFile, data_2_V_V_TVALID, "(port)data_2_V_V_TVALID");
    sc_trace(mVcdFile, data_2_V_V_TREADY, "(port)data_2_V_V_TREADY");
    sc_trace(mVcdFile, data_3_V_V_TDATA, "(port)data_3_V_V_TDATA");
    sc_trace(mVcdFile, data_3_V_V_TVALID, "(port)data_3_V_V_TVALID");
    sc_trace(mVcdFile, data_3_V_V_TREADY, "(port)data_3_V_V_TREADY");
    sc_trace(mVcdFile, res_0_V_V_TDATA, "(port)res_0_V_V_TDATA");
    sc_trace(mVcdFile, res_0_V_V_TVALID, "(port)res_0_V_V_TVALID");
    sc_trace(mVcdFile, res_0_V_V_TREADY, "(port)res_0_V_V_TREADY");
    sc_trace(mVcdFile, res_1_V_V_TDATA, "(port)res_1_V_V_TDATA");
    sc_trace(mVcdFile, res_1_V_V_TVALID, "(port)res_1_V_V_TVALID");
    sc_trace(mVcdFile, res_1_V_V_TREADY, "(port)res_1_V_V_TREADY");
    sc_trace(mVcdFile, res_2_V_V_TDATA, "(port)res_2_V_V_TDATA");
    sc_trace(mVcdFile, res_2_V_V_TVALID, "(port)res_2_V_V_TVALID");
    sc_trace(mVcdFile, res_2_V_V_TREADY, "(port)res_2_V_V_TREADY");
    sc_trace(mVcdFile, res_3_V_V_TDATA, "(port)res_3_V_V_TDATA");
    sc_trace(mVcdFile, res_3_V_V_TVALID, "(port)res_3_V_V_TVALID");
    sc_trace(mVcdFile, res_3_V_V_TREADY, "(port)res_3_V_V_TREADY");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, data_0_V_V_TDATA_blk_n, "data_0_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, icmp_ln79_fu_121_p2, "icmp_ln79_fu_121_p2");
    sc_trace(mVcdFile, data_1_V_V_TDATA_blk_n, "data_1_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, data_2_V_V_TDATA_blk_n, "data_2_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, data_3_V_V_TDATA_blk_n, "data_3_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, res_0_V_V_TDATA_blk_n, "res_0_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, icmp_ln79_reg_221, "icmp_ln79_reg_221");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, icmp_ln79_reg_221_pp0_iter1_reg, "icmp_ln79_reg_221_pp0_iter1_reg");
    sc_trace(mVcdFile, res_1_V_V_TDATA_blk_n, "res_1_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, res_2_V_V_TDATA_blk_n, "res_2_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, res_3_V_V_TDATA_blk_n, "res_3_V_V_TDATA_blk_n");
    sc_trace(mVcdFile, i_0_reg_110, "i_0_reg_110");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter1, "ap_block_state3_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state3_io, "ap_block_state3_io");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter2, "ap_block_state4_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state4_io, "ap_block_state4_io");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, i_fu_127_p2, "i_fu_127_p2");
    sc_trace(mVcdFile, tmp_V_fu_155_p3, "tmp_V_fu_155_p3");
    sc_trace(mVcdFile, tmp_V_reg_230, "tmp_V_reg_230");
    sc_trace(mVcdFile, tmp_V_2_fu_169_p3, "tmp_V_2_fu_169_p3");
    sc_trace(mVcdFile, tmp_V_2_reg_235, "tmp_V_2_reg_235");
    sc_trace(mVcdFile, tmp_V_4_fu_183_p3, "tmp_V_4_fu_183_p3");
    sc_trace(mVcdFile, tmp_V_4_reg_240, "tmp_V_4_reg_240");
    sc_trace(mVcdFile, tmp_V_6_fu_197_p3, "tmp_V_6_fu_197_p3");
    sc_trace(mVcdFile, tmp_V_6_reg_245, "tmp_V_6_reg_245");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, icmp_ln1494_fu_149_p2, "icmp_ln1494_fu_149_p2");
    sc_trace(mVcdFile, trunc_ln203_fu_133_p1, "trunc_ln203_fu_133_p1");
    sc_trace(mVcdFile, icmp_ln1494_1_fu_163_p2, "icmp_ln1494_1_fu_163_p2");
    sc_trace(mVcdFile, trunc_ln203_1_fu_137_p1, "trunc_ln203_1_fu_137_p1");
    sc_trace(mVcdFile, icmp_ln1494_2_fu_177_p2, "icmp_ln1494_2_fu_177_p2");
    sc_trace(mVcdFile, trunc_ln203_2_fu_141_p1, "trunc_ln203_2_fu_141_p1");
    sc_trace(mVcdFile, icmp_ln1494_3_fu_191_p2, "icmp_ln1494_3_fu_191_p2");
    sc_trace(mVcdFile, trunc_ln203_3_fu_145_p1, "trunc_ln203_3_fu_145_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, regslice_both_res_0_V_V_U_apdone_blk, "regslice_both_res_0_V_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_res_1_V_V_U_apdone_blk, "regslice_both_res_1_V_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_res_2_V_V_U_apdone_blk, "regslice_both_res_2_V_V_U_apdone_blk");
    sc_trace(mVcdFile, regslice_both_res_3_V_V_U_apdone_blk, "regslice_both_res_3_V_V_U_apdone_blk");
    sc_trace(mVcdFile, ap_block_state5, "ap_block_state5");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, regslice_both_data_0_V_V_U_apdone_blk, "regslice_both_data_0_V_V_U_apdone_blk");
    sc_trace(mVcdFile, data_0_V_V_TDATA_int, "data_0_V_V_TDATA_int");
    sc_trace(mVcdFile, data_0_V_V_TVALID_int, "data_0_V_V_TVALID_int");
    sc_trace(mVcdFile, data_0_V_V_TREADY_int, "data_0_V_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_data_0_V_V_U_ack_in, "regslice_both_data_0_V_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_data_1_V_V_U_apdone_blk, "regslice_both_data_1_V_V_U_apdone_blk");
    sc_trace(mVcdFile, data_1_V_V_TDATA_int, "data_1_V_V_TDATA_int");
    sc_trace(mVcdFile, data_1_V_V_TVALID_int, "data_1_V_V_TVALID_int");
    sc_trace(mVcdFile, data_1_V_V_TREADY_int, "data_1_V_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_data_1_V_V_U_ack_in, "regslice_both_data_1_V_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_data_2_V_V_U_apdone_blk, "regslice_both_data_2_V_V_U_apdone_blk");
    sc_trace(mVcdFile, data_2_V_V_TDATA_int, "data_2_V_V_TDATA_int");
    sc_trace(mVcdFile, data_2_V_V_TVALID_int, "data_2_V_V_TVALID_int");
    sc_trace(mVcdFile, data_2_V_V_TREADY_int, "data_2_V_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_data_2_V_V_U_ack_in, "regslice_both_data_2_V_V_U_ack_in");
    sc_trace(mVcdFile, regslice_both_data_3_V_V_U_apdone_blk, "regslice_both_data_3_V_V_U_apdone_blk");
    sc_trace(mVcdFile, data_3_V_V_TDATA_int, "data_3_V_V_TDATA_int");
    sc_trace(mVcdFile, data_3_V_V_TVALID_int, "data_3_V_V_TVALID_int");
    sc_trace(mVcdFile, data_3_V_V_TREADY_int, "data_3_V_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_data_3_V_V_U_ack_in, "regslice_both_data_3_V_V_U_ack_in");
    sc_trace(mVcdFile, res_0_V_V_TDATA_int, "res_0_V_V_TDATA_int");
    sc_trace(mVcdFile, res_0_V_V_TVALID_int, "res_0_V_V_TVALID_int");
    sc_trace(mVcdFile, res_0_V_V_TREADY_int, "res_0_V_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_res_0_V_V_U_vld_out, "regslice_both_res_0_V_V_U_vld_out");
    sc_trace(mVcdFile, res_1_V_V_TDATA_int, "res_1_V_V_TDATA_int");
    sc_trace(mVcdFile, res_1_V_V_TVALID_int, "res_1_V_V_TVALID_int");
    sc_trace(mVcdFile, res_1_V_V_TREADY_int, "res_1_V_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_res_1_V_V_U_vld_out, "regslice_both_res_1_V_V_U_vld_out");
    sc_trace(mVcdFile, res_2_V_V_TDATA_int, "res_2_V_V_TDATA_int");
    sc_trace(mVcdFile, res_2_V_V_TVALID_int, "res_2_V_V_TVALID_int");
    sc_trace(mVcdFile, res_2_V_V_TREADY_int, "res_2_V_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_res_2_V_V_U_vld_out, "regslice_both_res_2_V_V_U_vld_out");
    sc_trace(mVcdFile, res_3_V_V_TDATA_int, "res_3_V_V_TDATA_int");
    sc_trace(mVcdFile, res_3_V_V_TVALID_int, "res_3_V_V_TVALID_int");
    sc_trace(mVcdFile, res_3_V_V_TREADY_int, "res_3_V_V_TREADY_int");
    sc_trace(mVcdFile, regslice_both_res_3_V_V_U_vld_out, "regslice_both_res_3_V_V_U_vld_out");
#endif

    }
}

relu_array_ap_fixed_ap_fixed_relu_config55_s::~relu_array_ap_fixed_ap_fixed_relu_config55_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete regslice_both_data_0_V_V_U;
    delete regslice_both_data_1_V_V_U;
    delete regslice_both_data_2_V_V_U;
    delete regslice_both_data_3_V_V_U;
    delete regslice_both_res_0_V_V_U;
    delete regslice_both_res_1_V_V_U;
    delete regslice_both_res_2_V_V_U;
    delete regslice_both_res_3_V_V_U;
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_0_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_1_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_2_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_3_V_V_U_apdone_blk.read())))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state2.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
            ap_enable_reg_pp0_iter2 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        i_0_reg_110 = i_fu_127_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        i_0_reg_110 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln79_reg_221 = icmp_ln79_fu_121_p2.read();
        icmp_ln79_reg_221_pp0_iter1_reg = icmp_ln79_reg_221.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_V_2_reg_235 = tmp_V_2_fu_169_p3.read();
        tmp_V_4_reg_240 = tmp_V_4_fu_183_p3.read();
        tmp_V_6_reg_245 = tmp_V_6_fu_197_p3.read();
        tmp_V_reg_230 = tmp_V_fu_155_p3.read();
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[2];
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && ((esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, data_0_V_V_TVALID_int.read())) || 
  (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, data_1_V_V_TVALID_int.read())) || 
  (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, data_2_V_V_TVALID_int.read())) || 
  (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
   esl_seteq<1,1,1>(ap_const_logic_0, data_3_V_V_TVALID_int.read()))));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  ((esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, data_0_V_V_TVALID_int.read())) || 
   (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, data_1_V_V_TVALID_int.read())) || 
   (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, data_2_V_V_TVALID_int.read())) || 
   (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, data_3_V_V_TVALID_int.read())))));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state3_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_boolean_1, ap_block_state4_io.read())) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  ((esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, data_0_V_V_TVALID_int.read())) || 
   (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, data_1_V_V_TVALID_int.read())) || 
   (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, data_2_V_V_TVALID_int.read())) || 
   (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
    esl_seteq<1,1,1>(ap_const_logic_0, data_3_V_V_TVALID_int.read())))));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = ((esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_0_V_V_TVALID_int.read())) || (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_1_V_V_TVALID_int.read())) || (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_2_V_V_TVALID_int.read())) || (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_0, data_3_V_V_TVALID_int.read())));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_state3_io() {
    ap_block_state3_io = ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_0_V_V_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_1_V_V_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_2_V_V_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_3_V_V_TREADY_int.read())));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_state3_pp0_stage0_iter1() {
    ap_block_state3_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_state4_io() {
    ap_block_state4_io = ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_0_V_V_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_1_V_V_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_2_V_V_TREADY_int.read())) || (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221_pp0_iter1_reg.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_0, res_3_V_V_TREADY_int.read())));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_state4_pp0_stage0_iter2() {
    ap_block_state4_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_block_state5() {
    ap_block_state5 = (esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_0_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_1_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_2_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_3_V_V_U_apdone_blk.read()));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_0_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_1_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_2_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_3_V_V_U_apdone_blk.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_0_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_1_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_2_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_3_V_V_U_apdone_blk.read())))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_0_V_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0))) {
        data_0_V_V_TDATA_blk_n = data_0_V_V_TVALID_int.read();
    } else {
        data_0_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_0_V_V_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, data_0_V_V_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_data_0_V_V_U_ack_in.read()))) {
        data_0_V_V_TREADY = ap_const_logic_1;
    } else {
        data_0_V_V_TREADY = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_0_V_V_TREADY_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_0_V_V_TREADY_int = ap_const_logic_1;
    } else {
        data_0_V_V_TREADY_int = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_1_V_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0))) {
        data_1_V_V_TDATA_blk_n = data_1_V_V_TVALID_int.read();
    } else {
        data_1_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_1_V_V_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, data_1_V_V_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_data_1_V_V_U_ack_in.read()))) {
        data_1_V_V_TREADY = ap_const_logic_1;
    } else {
        data_1_V_V_TREADY = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_1_V_V_TREADY_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_1_V_V_TREADY_int = ap_const_logic_1;
    } else {
        data_1_V_V_TREADY_int = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_2_V_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0))) {
        data_2_V_V_TDATA_blk_n = data_2_V_V_TVALID_int.read();
    } else {
        data_2_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_2_V_V_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, data_2_V_V_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_data_2_V_V_U_ack_in.read()))) {
        data_2_V_V_TREADY = ap_const_logic_1;
    } else {
        data_2_V_V_TREADY = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_2_V_V_TREADY_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_2_V_V_TREADY_int = ap_const_logic_1;
    } else {
        data_2_V_V_TREADY_int = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_3_V_V_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0))) {
        data_3_V_V_TDATA_blk_n = data_3_V_V_TVALID_int.read();
    } else {
        data_3_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_3_V_V_TREADY() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, data_3_V_V_TVALID.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_data_3_V_V_U_ack_in.read()))) {
        data_3_V_V_TREADY = ap_const_logic_1;
    } else {
        data_3_V_V_TREADY = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_data_3_V_V_TREADY_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        data_3_V_V_TREADY_int = ap_const_logic_1;
    } else {
        data_3_V_V_TREADY_int = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_i_fu_127_p2() {
    i_fu_127_p2 = (!i_0_reg_110.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(i_0_reg_110.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_icmp_ln1494_1_fu_163_p2() {
    icmp_ln1494_1_fu_163_p2 = (!data_1_V_V_TDATA_int.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_1_V_V_TDATA_int.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_icmp_ln1494_2_fu_177_p2() {
    icmp_ln1494_2_fu_177_p2 = (!data_2_V_V_TDATA_int.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_2_V_V_TDATA_int.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_icmp_ln1494_3_fu_191_p2() {
    icmp_ln1494_3_fu_191_p2 = (!data_3_V_V_TDATA_int.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_3_V_V_TDATA_int.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_icmp_ln1494_fu_149_p2() {
    icmp_ln1494_fu_149_p2 = (!data_0_V_V_TDATA_int.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(data_0_V_V_TDATA_int.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_icmp_ln79_fu_121_p2() {
    icmp_ln79_fu_121_p2 = (!i_0_reg_110.read().is_01() || !ap_const_lv10_268.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_110.read() == ap_const_lv10_268);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_0_V_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221_pp0_iter1_reg.read())))) {
        res_0_V_V_TDATA_blk_n = res_0_V_V_TREADY_int.read();
    } else {
        res_0_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_0_V_V_TDATA_int() {
    res_0_V_V_TDATA_int = esl_zext<16,15>(tmp_V_reg_230.read());
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_0_V_V_TVALID() {
    res_0_V_V_TVALID = regslice_both_res_0_V_V_U_vld_out.read();
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_0_V_V_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_0_V_V_TVALID_int = ap_const_logic_1;
    } else {
        res_0_V_V_TVALID_int = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_1_V_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221_pp0_iter1_reg.read())))) {
        res_1_V_V_TDATA_blk_n = res_1_V_V_TREADY_int.read();
    } else {
        res_1_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_1_V_V_TDATA_int() {
    res_1_V_V_TDATA_int = esl_zext<16,15>(tmp_V_2_reg_235.read());
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_1_V_V_TVALID() {
    res_1_V_V_TVALID = regslice_both_res_1_V_V_U_vld_out.read();
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_1_V_V_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_1_V_V_TVALID_int = ap_const_logic_1;
    } else {
        res_1_V_V_TVALID_int = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_2_V_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221_pp0_iter1_reg.read())))) {
        res_2_V_V_TDATA_blk_n = res_2_V_V_TREADY_int.read();
    } else {
        res_2_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_2_V_V_TDATA_int() {
    res_2_V_V_TDATA_int = esl_zext<16,15>(tmp_V_4_reg_240.read());
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_2_V_V_TVALID() {
    res_2_V_V_TVALID = regslice_both_res_2_V_V_U_vld_out.read();
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_2_V_V_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_2_V_V_TVALID_int = ap_const_logic_1;
    } else {
        res_2_V_V_TVALID_int = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_3_V_V_TDATA_blk_n() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read())) || 
         (esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221_pp0_iter1_reg.read())))) {
        res_3_V_V_TDATA_blk_n = res_3_V_V_TREADY_int.read();
    } else {
        res_3_V_V_TDATA_blk_n = ap_const_logic_1;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_3_V_V_TDATA_int() {
    res_3_V_V_TDATA_int = esl_zext<16,15>(tmp_V_6_reg_245.read());
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_3_V_V_TVALID() {
    res_3_V_V_TVALID = regslice_both_res_3_V_V_U_vld_out.read();
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_res_3_V_V_TVALID_int() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln79_reg_221.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        res_3_V_V_TVALID_int = ap_const_logic_1;
    } else {
        res_3_V_V_TVALID_int = ap_const_logic_0;
    }
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_tmp_V_2_fu_169_p3() {
    tmp_V_2_fu_169_p3 = (!icmp_ln1494_1_fu_163_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_1_fu_163_p2.read()[0].to_bool())? trunc_ln203_1_fu_137_p1.read(): ap_const_lv15_0);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_tmp_V_4_fu_183_p3() {
    tmp_V_4_fu_183_p3 = (!icmp_ln1494_2_fu_177_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_2_fu_177_p2.read()[0].to_bool())? trunc_ln203_2_fu_141_p1.read(): ap_const_lv15_0);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_tmp_V_6_fu_197_p3() {
    tmp_V_6_fu_197_p3 = (!icmp_ln1494_3_fu_191_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_3_fu_191_p2.read()[0].to_bool())? trunc_ln203_3_fu_145_p1.read(): ap_const_lv15_0);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_tmp_V_fu_155_p3() {
    tmp_V_fu_155_p3 = (!icmp_ln1494_fu_149_p2.read()[0].is_01())? sc_lv<15>(): ((icmp_ln1494_fu_149_p2.read()[0].to_bool())? trunc_ln203_fu_133_p1.read(): ap_const_lv15_0);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_trunc_ln203_1_fu_137_p1() {
    trunc_ln203_1_fu_137_p1 = data_1_V_V_TDATA_int.read().range(15-1, 0);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_trunc_ln203_2_fu_141_p1() {
    trunc_ln203_2_fu_141_p1 = data_2_V_V_TDATA_int.read().range(15-1, 0);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_trunc_ln203_3_fu_145_p1() {
    trunc_ln203_3_fu_145_p1 = data_3_V_V_TDATA_int.read().range(15-1, 0);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_trunc_ln203_fu_133_p1() {
    trunc_ln203_fu_133_p1 = data_0_V_V_TDATA_int.read().range(15-1, 0);
}

void relu_array_ap_fixed_ap_fixed_relu_config55_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(icmp_ln79_fu_121_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && !(esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_0_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_1_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_2_V_V_U_apdone_blk.read()) || esl_seteq<1,1,1>(ap_const_logic_1, regslice_both_res_3_V_V_U_apdone_blk.read())))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

}

