// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.232000,HLS_SYN_LAT=12323,HLS_SYN_TPT=12324,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=63,HLS_SYN_LUT=271,HLS_VERSION=2019_2}" *)

module myproject (
        em_barrel_V_V_TDATA,
        layer55_out_V_V_TDATA,
        const_size_in_1,
        const_size_out_1,
        ap_clk,
        ap_rst_n,
        const_size_in_1_ap_vld,
        const_size_out_1_ap_vld,
        ap_start,
        ap_done,
        em_barrel_V_V_TVALID,
        em_barrel_V_V_TREADY,
        layer55_out_V_V_TVALID,
        layer55_out_V_V_TREADY,
        ap_ready,
        ap_idle
);


input  [31:0] em_barrel_V_V_TDATA;
output  [31:0] layer55_out_V_V_TDATA;
output  [15:0] const_size_in_1;
output  [15:0] const_size_out_1;
input   ap_clk;
input   ap_rst_n;
output   const_size_in_1_ap_vld;
output   const_size_out_1_ap_vld;
input   ap_start;
output   ap_done;
input   em_barrel_V_V_TVALID;
output   em_barrel_V_V_TREADY;
output   layer55_out_V_V_TVALID;
input   layer55_out_V_V_TREADY;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    Block_proc_U0_ap_start;
wire    Block_proc_U0_ap_done;
wire    Block_proc_U0_ap_continue;
wire    Block_proc_U0_ap_idle;
wire    Block_proc_U0_ap_ready;
wire   [15:0] Block_proc_U0_const_size_in_1;
wire    Block_proc_U0_const_size_in_1_ap_vld;
wire   [15:0] Block_proc_U0_const_size_out_1;
wire    Block_proc_U0_const_size_out_1_ap_vld;
wire    ap_sync_continue;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_start;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_done;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_continue;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_idle;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_data_V_V_TREADY;
wire   [31:0] normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TDATA;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TVALID;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_proc_U0_ap_ready;
wire    ap_sync_Block_proc_U0_ap_ready;
reg   [1:0] Block_proc_U0_ap_ready_count;
reg    ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready;
wire    ap_sync_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready;
reg   [1:0] normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count;
wire    Block_proc_U0_start_full_n;
wire    Block_proc_U0_start_write;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_start_full_n;
wire    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_proc_U0_ap_ready = 1'b0;
#0 Block_proc_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready = 1'b0;
#0 normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count = 2'd0;
end

Block_proc Block_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_proc_U0_ap_start),
    .ap_done(Block_proc_U0_ap_done),
    .ap_continue(Block_proc_U0_ap_continue),
    .ap_idle(Block_proc_U0_ap_idle),
    .ap_ready(Block_proc_U0_ap_ready),
    .const_size_in_1(Block_proc_U0_const_size_in_1),
    .const_size_in_1_ap_vld(Block_proc_U0_const_size_in_1_ap_vld),
    .const_size_out_1(Block_proc_U0_const_size_out_1),
    .const_size_out_1_ap_vld(Block_proc_U0_const_size_out_1_ap_vld)
);

normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_s normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_start),
    .ap_done(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_done),
    .ap_continue(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_continue),
    .ap_idle(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_idle),
    .ap_ready(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready),
    .data_V_V_TDATA(em_barrel_V_V_TDATA),
    .data_V_V_TVALID(em_barrel_V_V_TVALID),
    .data_V_V_TREADY(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_data_V_V_TREADY),
    .res_V_V_TDATA(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TDATA),
    .res_V_V_TVALID(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TVALID),
    .res_V_V_TREADY(layer55_out_V_V_TREADY)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_proc_U0_ap_ready <= ap_sync_Block_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready <= ap_sync_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_sync_ready == 1'b1) & (1'b0 == Block_proc_U0_ap_ready))) begin
        Block_proc_U0_ap_ready_count <= (Block_proc_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == Block_proc_U0_ap_ready))) begin
        Block_proc_U0_ap_ready_count <= (Block_proc_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready == 1'b0) & (ap_sync_ready == 1'b1))) begin
        normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count <= (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready == 1'b1))) begin
        normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count <= (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count + 2'd1);
    end
end

assign Block_proc_U0_ap_continue = ap_sync_done;

assign Block_proc_U0_ap_start = ((ap_sync_reg_Block_proc_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_proc_U0_start_full_n = 1'b1;

assign Block_proc_U0_start_write = 1'b0;

assign ap_done = ap_sync_done;

assign ap_idle = (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_idle & Block_proc_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_Block_proc_U0_ap_ready = (ap_sync_reg_Block_proc_U0_ap_ready | Block_proc_U0_ap_ready);

assign ap_sync_continue = ap_sync_done;

assign ap_sync_done = (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_done & Block_proc_U0_ap_done);

assign ap_sync_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready = (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready | ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready);

assign ap_sync_ready = (ap_sync_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready & ap_sync_Block_proc_U0_ap_ready);

assign const_size_in_1 = Block_proc_U0_const_size_in_1;

assign const_size_in_1_ap_vld = Block_proc_U0_const_size_in_1_ap_vld;

assign const_size_out_1 = Block_proc_U0_const_size_out_1;

assign const_size_out_1_ap_vld = Block_proc_U0_const_size_out_1_ap_vld;

assign em_barrel_V_V_TREADY = normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_data_V_V_TREADY;

assign layer55_out_V_V_TDATA = normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TDATA;

assign layer55_out_V_V_TVALID = normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TVALID;

assign normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_continue = ap_sync_done;

assign normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_start = ((ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready ^ 1'b1) & ap_start);

assign normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_start_full_n = 1'b1;

assign normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_start_write = 1'b0;

endmodule //myproject
