-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    input_1_V_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
    layer2_out_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    const_size_in_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    const_size_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    w2_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w2_V_ce0 : OUT STD_LOGIC;
    w2_V_d0 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w2_V_q0 : IN STD_LOGIC_VECTOR (127 downto 0);
    w2_V_we0 : OUT STD_LOGIC;
    w2_V_address1 : OUT STD_LOGIC_VECTOR (6 downto 0);
    w2_V_ce1 : OUT STD_LOGIC;
    w2_V_d1 : OUT STD_LOGIC_VECTOR (127 downto 0);
    w2_V_q1 : IN STD_LOGIC_VECTOR (127 downto 0);
    w2_V_we1 : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    const_size_in_1_ap_vld : OUT STD_LOGIC;
    const_size_out_1_ap_vld : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    input_1_V_V_TVALID : IN STD_LOGIC;
    input_1_V_V_TREADY : OUT STD_LOGIC;
    layer2_out_V_V_TVALID : OUT STD_LOGIC;
    layer2_out_V_V_TREADY : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xczu9eg-ffvb1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.127000,HLS_SYN_LAT=7743,HLS_SYN_TPT=7727,HLS_SYN_MEM=8,HLS_SYN_DSP=1,HLS_SYN_FF=3093,HLS_SYN_LUT=3636,HLS_VERSION=2019_2}";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal Block_proc_U0_ap_start : STD_LOGIC;
    signal Block_proc_U0_ap_done : STD_LOGIC;
    signal Block_proc_U0_ap_continue : STD_LOGIC;
    signal Block_proc_U0_ap_idle : STD_LOGIC;
    signal Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_const_size_in_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal Block_proc_U0_const_size_in_1_ap_vld : STD_LOGIC;
    signal Block_proc_U0_const_size_out_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal Block_proc_U0_const_size_out_1_ap_vld : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_start : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_done : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_continue : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_idle : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_data_V_V_TREADY : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_res_V_V_din : STD_LOGIC_VECTOR (15 downto 0);
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_res_V_V_write : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_start : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_done : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_continue : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_idle : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_data_V_V_read : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_res_V_V_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_res_V_V_TVALID : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_weights_V_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_weights_V_ce0 : STD_LOGIC;
    signal layer4_out_V_V_full_n : STD_LOGIC;
    signal layer4_out_V_V_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal layer4_out_V_V_empty_n : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_Block_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal Block_proc_U0_start_full_n : STD_LOGIC;
    signal Block_proc_U0_start_write : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_start_full_n : STD_LOGIC;
    signal zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_start_write : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_start_full_n : STD_LOGIC;
    signal conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_start_write : STD_LOGIC;

    component Block_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        const_size_in_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        const_size_in_1_ap_vld : OUT STD_LOGIC;
        const_size_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        const_size_out_1_ap_vld : OUT STD_LOGIC );
    end component;


    component zeropad2d_cl_me_ap_fixed_ap_fixed_config4_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_V_V_TDATA : IN STD_LOGIC_VECTOR (15 downto 0);
        data_V_V_TVALID : IN STD_LOGIC;
        data_V_V_TREADY : OUT STD_LOGIC;
        res_V_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_V_V_full_n : IN STD_LOGIC;
        res_V_V_write : OUT STD_LOGIC );
    end component;


    component conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_V_V_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        data_V_V_empty_n : IN STD_LOGIC;
        data_V_V_read : OUT STD_LOGIC;
        res_V_V_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        res_V_V_TVALID : OUT STD_LOGIC;
        res_V_V_TREADY : IN STD_LOGIC;
        weights_V_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        weights_V_ce0 : OUT STD_LOGIC;
        weights_V_q0 : IN STD_LOGIC_VECTOR (127 downto 0) );
    end component;


    component fifo_w16_d25_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    Block_proc_U0 : component Block_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_proc_U0_ap_start,
        ap_done => Block_proc_U0_ap_done,
        ap_continue => Block_proc_U0_ap_continue,
        ap_idle => Block_proc_U0_ap_idle,
        ap_ready => Block_proc_U0_ap_ready,
        const_size_in_1 => Block_proc_U0_const_size_in_1,
        const_size_in_1_ap_vld => Block_proc_U0_const_size_in_1_ap_vld,
        const_size_out_1 => Block_proc_U0_const_size_out_1,
        const_size_out_1_ap_vld => Block_proc_U0_const_size_out_1_ap_vld);

    zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0 : component zeropad2d_cl_me_ap_fixed_ap_fixed_config4_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_start,
        ap_done => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_done,
        ap_continue => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_continue,
        ap_idle => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_idle,
        ap_ready => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready,
        data_V_V_TDATA => input_1_V_V_TDATA,
        data_V_V_TVALID => input_1_V_V_TVALID,
        data_V_V_TREADY => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_data_V_V_TREADY,
        res_V_V_din => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_res_V_V_din,
        res_V_V_full_n => layer4_out_V_V_full_n,
        res_V_V_write => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_res_V_V_write);

    conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0 : component conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_start,
        ap_done => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_done,
        ap_continue => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_continue,
        ap_idle => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_idle,
        ap_ready => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready,
        data_V_V_dout => layer4_out_V_V_dout,
        data_V_V_empty_n => layer4_out_V_V_empty_n,
        data_V_V_read => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_data_V_V_read,
        res_V_V_TDATA => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_res_V_V_TDATA,
        res_V_V_TVALID => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_res_V_V_TVALID,
        res_V_V_TREADY => layer2_out_V_V_TREADY,
        weights_V_address0 => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_weights_V_address0,
        weights_V_ce0 => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_weights_V_ce0,
        weights_V_q0 => w2_V_q0);

    layer4_out_V_V_U : component fifo_w16_d25_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_res_V_V_din,
        if_full_n => layer4_out_V_V_full_n,
        if_write => zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_res_V_V_write,
        if_dout => layer4_out_V_V_dout,
        if_empty_n => layer4_out_V_V_empty_n,
        if_read => conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_data_V_V_read);





    ap_sync_reg_Block_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Block_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Block_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Block_proc_U0_ap_ready <= ap_sync_Block_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready <= ap_sync_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready <= ap_sync_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    Block_proc_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_0 = Block_proc_U0_ap_ready) and (ap_sync_ready = ap_const_logic_1))) then 
                Block_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_proc_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (ap_const_logic_1 = Block_proc_U0_ap_ready))) then 
                Block_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_proc_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready_count <= std_logic_vector(unsigned(conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready = ap_const_logic_1))) then 
                conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready_count <= std_logic_vector(unsigned(conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready_count <= std_logic_vector(unsigned(zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready = ap_const_logic_1))) then 
                zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready_count <= std_logic_vector(unsigned(zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    Block_proc_U0_ap_continue <= ap_sync_done;
    Block_proc_U0_ap_start <= ((ap_sync_reg_Block_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Block_proc_U0_start_full_n <= ap_const_logic_1;
    Block_proc_U0_start_write <= ap_const_logic_0;
    ap_done <= ap_sync_done;
    ap_idle <= (zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_idle and conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_idle and Block_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_Block_proc_U0_ap_ready <= (ap_sync_reg_Block_proc_U0_ap_ready or Block_proc_U0_ap_ready);
    ap_sync_continue <= ap_sync_done;
    ap_sync_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready <= (conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready or ap_sync_reg_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready);
    ap_sync_done <= (conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_done and Block_proc_U0_ap_done);
    ap_sync_ready <= (ap_sync_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready and ap_sync_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready and ap_sync_Block_proc_U0_ap_ready);
    ap_sync_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready <= (zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready or ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready);
    const_size_in_1 <= Block_proc_U0_const_size_in_1;
    const_size_in_1_ap_vld <= Block_proc_U0_const_size_in_1_ap_vld;
    const_size_out_1 <= Block_proc_U0_const_size_out_1;
    const_size_out_1_ap_vld <= Block_proc_U0_const_size_out_1_ap_vld;
    conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_continue <= ap_sync_done;
    conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_start <= ((ap_sync_reg_conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_ap_ready xor ap_const_logic_1) and ap_start);
    conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_start_full_n <= ap_const_logic_1;
    conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_start_write <= ap_const_logic_0;
    input_1_V_V_TREADY <= zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_data_V_V_TREADY;
    layer2_out_V_V_TDATA <= conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_res_V_V_TDATA;
    layer2_out_V_V_TVALID <= conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_res_V_V_TVALID;
    w2_V_address0 <= conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_weights_V_address0;
    w2_V_address1 <= ap_const_lv7_0;
    w2_V_ce0 <= conv_2d_cl_me_ap_fixed_ap_fixed_16_14_5_3_0_config2_U0_weights_V_ce0;
    w2_V_ce1 <= ap_const_logic_0;
    w2_V_d0 <= ap_const_lv128_lc_1;
    w2_V_d1 <= ap_const_lv128_lc_1;
    w2_V_we0 <= ap_const_logic_0;
    w2_V_we1 <= ap_const_logic_0;
    zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_continue <= ap_const_logic_1;
    zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_start <= ((ap_sync_reg_zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_ap_ready xor ap_const_logic_1) and ap_start);
    zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_start_full_n <= ap_const_logic_1;
    zeropad2d_cl_me_ap_fixed_ap_fixed_config4_U0_start_write <= ap_const_logic_0;
end behav;
