-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject is
port (
    em_barrel_V_V_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    layer55_out_V_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    const_size_in_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    const_size_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    const_size_in_1_ap_vld : OUT STD_LOGIC;
    const_size_out_1_ap_vld : OUT STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    em_barrel_V_V_TVALID : IN STD_LOGIC;
    em_barrel_V_V_TREADY : OUT STD_LOGIC;
    layer55_out_V_V_TVALID : OUT STD_LOGIC;
    layer55_out_V_V_TREADY : IN STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC );
end;


architecture behav of myproject is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "myproject,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xcvu9p-flgb2104-2-i,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.232000,HLS_SYN_LAT=12323,HLS_SYN_TPT=12324,HLS_SYN_MEM=0,HLS_SYN_DSP=4,HLS_SYN_FF=63,HLS_SYN_LUT=271,HLS_VERSION=2019_2}";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal Block_proc_U0_ap_start : STD_LOGIC;
    signal Block_proc_U0_ap_done : STD_LOGIC;
    signal Block_proc_U0_ap_continue : STD_LOGIC;
    signal Block_proc_U0_ap_idle : STD_LOGIC;
    signal Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_const_size_in_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal Block_proc_U0_const_size_in_1_ap_vld : STD_LOGIC;
    signal Block_proc_U0_const_size_out_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal Block_proc_U0_const_size_out_1_ap_vld : STD_LOGIC;
    signal ap_sync_continue : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_start : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_done : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_continue : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_idle : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_data_V_V_TREADY : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TVALID : STD_LOGIC;
    signal ap_sync_done : STD_LOGIC;
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_Block_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_Block_proc_U0_ap_ready : STD_LOGIC;
    signal Block_proc_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal Block_proc_U0_start_full_n : STD_LOGIC;
    signal Block_proc_U0_start_write : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_start_full_n : STD_LOGIC;
    signal normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_start_write : STD_LOGIC;

    component Block_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        const_size_in_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        const_size_in_1_ap_vld : OUT STD_LOGIC;
        const_size_out_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        const_size_out_1_ap_vld : OUT STD_LOGIC );
    end component;


    component normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_V_V_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        data_V_V_TVALID : IN STD_LOGIC;
        data_V_V_TREADY : OUT STD_LOGIC;
        res_V_V_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        res_V_V_TVALID : OUT STD_LOGIC;
        res_V_V_TREADY : IN STD_LOGIC );
    end component;



begin
    Block_proc_U0 : component Block_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => Block_proc_U0_ap_start,
        ap_done => Block_proc_U0_ap_done,
        ap_continue => Block_proc_U0_ap_continue,
        ap_idle => Block_proc_U0_ap_idle,
        ap_ready => Block_proc_U0_ap_ready,
        const_size_in_1 => Block_proc_U0_const_size_in_1,
        const_size_in_1_ap_vld => Block_proc_U0_const_size_in_1_ap_vld,
        const_size_out_1 => Block_proc_U0_const_size_out_1,
        const_size_out_1_ap_vld => Block_proc_U0_const_size_out_1_ap_vld);

    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0 : component normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_start,
        ap_done => normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_done,
        ap_continue => normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_continue,
        ap_idle => normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_idle,
        ap_ready => normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready,
        data_V_V_TDATA => em_barrel_V_V_TDATA,
        data_V_V_TVALID => em_barrel_V_V_TVALID,
        data_V_V_TREADY => normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_data_V_V_TREADY,
        res_V_V_TDATA => normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TDATA,
        res_V_V_TVALID => normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TVALID,
        res_V_V_TREADY => layer55_out_V_V_TREADY);





    ap_sync_reg_Block_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_Block_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_Block_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_Block_proc_U0_ap_ready <= ap_sync_Block_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready <= ap_sync_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    Block_proc_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_sync_ready = ap_const_logic_1) and (ap_const_logic_0 = Block_proc_U0_ap_ready))) then 
                Block_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_proc_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (ap_const_logic_1 = Block_proc_U0_ap_ready))) then 
                Block_proc_U0_ap_ready_count <= std_logic_vector(unsigned(Block_proc_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;

    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready = ap_const_logic_0) and (ap_sync_ready = ap_const_logic_1))) then 
                normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count <= std_logic_vector(unsigned(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count) - unsigned(ap_const_lv2_1));
            elsif (((ap_sync_ready = ap_const_logic_0) and (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready = ap_const_logic_1))) then 
                normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count <= std_logic_vector(unsigned(normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready_count) + unsigned(ap_const_lv2_1));
            end if; 
        end if;
    end process;
    Block_proc_U0_ap_continue <= ap_sync_done;
    Block_proc_U0_ap_start <= ((ap_sync_reg_Block_proc_U0_ap_ready xor ap_const_logic_1) and ap_start);
    Block_proc_U0_start_full_n <= ap_const_logic_1;
    Block_proc_U0_start_write <= ap_const_logic_0;
    ap_done <= ap_sync_done;
    ap_idle <= (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_idle and Block_proc_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_Block_proc_U0_ap_ready <= (ap_sync_reg_Block_proc_U0_ap_ready or Block_proc_U0_ap_ready);
    ap_sync_continue <= ap_sync_done;
    ap_sync_done <= (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_done and Block_proc_U0_ap_done);
    ap_sync_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready <= (normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready or ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready);
    ap_sync_ready <= (ap_sync_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready and ap_sync_Block_proc_U0_ap_ready);
    const_size_in_1 <= Block_proc_U0_const_size_in_1;
    const_size_in_1_ap_vld <= Block_proc_U0_const_size_in_1_ap_vld;
    const_size_out_1 <= Block_proc_U0_const_size_out_1;
    const_size_out_1_ap_vld <= Block_proc_U0_const_size_out_1_ap_vld;
    em_barrel_V_V_TREADY <= normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_data_V_V_TREADY;
    layer55_out_V_V_TDATA <= normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TDATA;
    layer55_out_V_V_TVALID <= normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_res_V_V_TVALID;
    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_continue <= ap_sync_done;
    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_start <= ((ap_sync_reg_normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_ap_ready xor ap_const_logic_1) and ap_start);
    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_start_full_n <= ap_const_logic_1;
    normalize_me_ap_fixed_ap_fixed_32_16_5_3_0_config3_U0_start_write <= ap_const_logic_0;
end behav;
